# Generated by Django 5.2.11 on 2026-03-05 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("otto", "0016_alter_notification_text_alter_notification_text_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(default="Untitled request", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_lang",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "target_lang",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        default="fr",
                        max_length=10,
                    ),
                ),
                (
                    "access_controls",
                    models.ManyToManyField(related_name="+", to="otto.accesscontrol"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutputFile",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="translate_output_files/"
                    ),
                ),
                ("file_name", models.TextField(default="tmp")),
                (
                    "celery_task_ids",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "access_controls",
                    models.ManyToManyField(related_name="+", to="otto.accesscontrol"),
                ),
                (
                    "user_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_files",
                        to="translate.userrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InputFile",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("file", models.FileField(upload_to="translate_input_files/")),
                ("original_filename", models.CharField(max_length=500)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "access_controls",
                    models.ManyToManyField(related_name="+", to="otto.accesscontrol"),
                ),
                (
                    "user_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_files",
                        to="translate.userrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
