# Generated by Django 5.2.11 on 2026-03-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outputfile",
            name="usd_cost",
            field=models.FloatField(default=0.0),
        ),
    ]
