model_list:
  - model_name: gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_KEY
      api_version: os.environ/AZURE_OPENAI_VERSION
  - model_name: gpt-4.1
    litellm_params:
      model: azure/gpt-4.1
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_KEY
      api_version: os.environ/AZURE_OPENAI_VERSION
  - model_name: o3-mini
    litellm_params:
      model: azure/o3-mini
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_KEY
      api_version: os.environ/AZURE_OPENAI_VERSION
  - model_name: gpt-4o-mini
    litellm_params:
      model: azure/gpt-4o-mini
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_KEY
      api_version: os.environ/AZURE_OPENAI_VERSION
  - model_name: text-embedding-3-large
    litellm_params:
      model: azure/text-embedding-3-large
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_KEY
      api_version: os.environ/AZURE_OPENAI_VERSION
  - model_name: Phi-4
    litellm_params:
      model: azure_ai/Phi-4
      api_base: os.environ/AZURE_AI_SERVICES_ENDPOINT
      api_key: os.environ/AZURE_AI_SERVICES_KEY

general_settings:
  master_key: sk-1234
  database_url: "postgresql://postgres:password@postgres-service:5432/litellm"

litellm_settings:
  ssl_verify: false
  drop_params: true
