model_list:
  - model_name: gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_KEY
      api_version: os.environ/AZURE_OPENAI_VERSION
  - model_name: gpt-4.1
    litellm_params:
      model: azure/gpt-4.1
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_KEY
      api_version: os.environ/AZURE_OPENAI_VERSION
  - model_name: gpt-4.1-mini
    litellm_params:
      model: azure/gpt-4.1-mini
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_KEY
      api_version: os.environ/AZURE_OPENAI_VERSION
  - model_name: o3-mini
    litellm_params:
      model: azure/o3-mini
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_KEY
      api_version: os.environ/AZURE_OPENAI_VERSION
  - model_name: gpt-4o-mini
    litellm_params:
      model: azure/gpt-4o-mini
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_KEY
      api_version: os.environ/AZURE_OPENAI_VERSION
  - model_name: text-embedding-3-large
    litellm_params:
      model: azure/text-embedding-3-large
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_key: os.environ/AZURE_OPENAI_KEY
      api_version: os.environ/AZURE_OPENAI_VERSION
  - model_name: Phi-4
    litellm_params:
      model: azure_ai/Phi-4
      api_base: os.environ/AZURE_AI_SERVICES_ENDPOINT
      api_key: os.environ/AZURE_AI_SERVICES_KEY
  - model_name: MAI-DS-R1
    litellm_params:
      model: azure_ai/MAI-DS-R1
      api_base: os.environ/AZURE_AI_SERVICES_ENDPOINT
      api_key: os.environ/AZURE_AI_SERVICES_KEY
  - model_name: groq-llama-4-scout
    litellm_params:
      model: groq/meta-llama/llama-4-scout-17b-16e-instruct
      api_key: os.environ/GROQ_KEY
  - model_name: groq-llama-4-maverick
    litellm_params:
      model: groq/meta-llama/llama-4-maverick-17b-128e-instruct
      api_key: os.environ/GROQ_KEY
  - model_name: groq-QwQ-32B
    litellm_params:
      model: groq/qwen-qwq-32b
      api_key: os.environ/GROQ_KEY
  - model_name: fireworks-Qwen3-235B
    litellm_params:
      model: fireworks_ai/accounts/fireworks/models/qwen3-235b-a22b
      api_key: os.environ/FIREWORKS_KEY
  - model_name: fireworks-Qwen3-30B
    litellm_params:
      model: fireworks_ai/accounts/fireworks/models/qwen3-30b-a3b
      api_key: os.environ/FIREWORKS_KEY
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash-preview-05-20
      api_key: os.environ/GEMINI_KEY
  - model_name: gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro-preview-05-06
      api_key: os.environ/GEMINI_KEY
  - model_name: cerebras-llama-4-scout
    litellm_params:
      model: cerebras/llama-4-scout-17b-16e-instruct
      api_key: os.environ/CEREBRAS_KEY
  - model_name: cerebras-qwen-3-32b
    litellm_params:
      model: cerebras/qwen-3-32b
      api_key: os.environ/CEREBRAS_KEY
  - model_name: claude-opus-4
    litellm_params:
      model: anthropic/claude-opus-4-20250514
      api_key: os.environ/ANTHROPIC_KEY
  - model_name: claude-sonnet-4
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514
      api_key: os.environ/ANTHROPIC_KEY
  - model_name: command-a 
    litellm_params:
      model: command-a-03-2025
      api_key: "os.environ/COHERE_KEY"

general_settings:
  master_key: sk-1234
  database_url: "postgresql://postgres:password@postgres-service:5432/litellm"
  disable_spend_logs: True   # Disable writing spend logs to DB
  disable_error_logs: True   # Only disable writing error logs to DB, regular spend logs will still be written unless `disable_spend_logs: True`

litellm_settings:
  ssl_verify: false
  drop_params: true  # Drop parameters that are not in the model's schema
