apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    deployment: redis
  namespace: otto
spec:
  selector:
    matchLabels:
      pod: redis
  replicas: 1
  template:
    metadata:
      labels:
        pod: redis
    spec:
      containers:
      - name: redis
        # TODO: probably best to use a targeted version
        image: redis:7.0.11-bullseye        
        ports:
        - containerPort: 6379
        # TODO: add resource limits
