# # List the cronjobs
# kubectl get cronjobs -n otto

# # List the jobs
# kubectl get jobs -n otto

# # List the configmaps
# kubectl get configmaps -n otto

# # Apply the configuration
# kubectl apply -f backups.yaml

# # Trigger the job manually
# kubectl create job --from=cronjob/backup-cron manual-backup-test-1 -n otto

# # Check the logs of the job
# kubectl logs job/manual-backup-test-1 -n otto -f

# # Delete the job
# kubectl delete job manual-backup-test-1 -n otto

# # Delete the configmap
# kubectl delete configmap backup-script -n otto

# # Delete the cronjob
# kubectl delete cronjob backup-cron -n otto


apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-script
  namespace: otto
data:
  backup.sh: |
    #!/bin/bash
    # The content of this script will be replaced by the external file

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cron
  namespace: otto
spec:
  schedule: "0 2 * * *"  # Run daily at 2:00 AM
  timeZone: "America/Toronto"  # Specify Toronto timezone
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: ${ACR_NAME}.azurecr.io/db-backup:latest
            envFrom:
              - configMapRef:
                  name: otto-configmap
            env:
              - name: DJANGODB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: azure-keyvault-secrets
                    key: djangodbpasswordkey
              - name: VECTORDB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: azure-keyvault-secrets
                    key: vectordbpasswordkey
              - name: AZURE_STORAGE_ACCOUNT_KEY
                valueFrom:
                  secretKeyRef:
                    name: azure-keyvault-secrets
                    key: storageaccountkey
            volumeMounts:
            - name: script-volume
              mountPath: /scripts
            command: ["/bin/bash"]
            args:
            - -c
            - /scripts/backup.sh
          volumes:
          - name: script-volume
            configMap:
              name: backup-script
              defaultMode: 0755
          restartPolicy: OnFailure
