# SC-13: Use of approved cryptographic algorithms 
# (Explicitly using ECDSA with P-256 curve, compliant with NIST SP 800-56A)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: otto@justice.gc.ca
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
  # Explicitly specify the private key algorithm
  privateKeyAlgorithm: ECDSA
  privateKeySize: 256  # P-256 curve
