# CM-8 & CM-9: Defines the application's components within the AKS cluster

# SC-13: Use of approved cryptographic algorithms
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: otto@justice.gc.ca
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
    - dns01:
        azureDNS:
          subscriptionID: ${DNS_ZONE_SUBSCRIPTION_ID}
          resourceGroupName: ${DNS_ZONE_RESOURCE_GROUP_NAME}
          hostedZoneName: ${DOMAIN_NAME}
          environment: AzurePublicCloud
          managedIdentity:
            clientID: ${OTTO_IDENTITY_ID}
      selector:
        dnsZones:
          - "${DOMAIN_NAME}"

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otto-cert
  namespace: otto
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - ${DOMAIN_NAME}
  privateKey:
    rotationPolicy: Always # Generate a new private key each time the certificate is renewed or reissued  
