# CM-8 & CM-9: Defines the application's components within the AKS cluster

apiVersion: apps/v1
kind: StatefulSet # Required for stable network identity
metadata:
  name: redis
  namespace: otto
spec:
  replicas: 1
  serviceName: "redis-service"  # Required for stable network identity
  selector:
    matchLabels:
      pod: redis
  template:
    metadata:
      labels:
        pod: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0.11-bullseye        
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "${REDIS_CPU_MIN}"
            memory: "${REDIS_MEMORY_MIN}Gi"
          limits:
            cpu: "${REDIS_CPU_MAX}"
            memory: "${REDIS_MEMORY_MAX}Gi"
        # Add readiness and liveness probes
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 20

---

apiVersion: v1
kind: Service # Exposes the Redis instance to other components within the cluster 
metadata:
  name: redis-service  
  namespace: otto
spec:
  selector:
    pod: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
