# CM-8 & CM-9: Defines the application's components within the AKS cluster

apiVersion: apps/v1
kind: StatefulSet # Required for stable network identity
metadata:
  name: redis
  namespace: otto
spec:
  serviceName: "redis-service"  # Required for stable network identity
  selector:
    matchLabels:
      pod: redis
  replicas: 1
  template:
    metadata:
      labels:
        pod: redis
    spec:
      containers:
      - name: redis
        # TODO: probably best to use a targeted version
        image: redis:7.0.11-bullseye        
        ports:
        - containerPort: 6379
        # TODO: add resource limits

---

apiVersion: v1
kind: Service # Exposes the Redis instance to other components within the cluster 
metadata:
  name: redis-service  
  namespace: otto
spec:
  selector:
    pod: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
