apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-tls-secret
  namespace: otto
spec:
  provider: azure
  parameters:
    keyvaultName: "${CERT_KEYVAULT_NAME}"
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "${AKS_IDENTITY_ID}"
    objects: |
      array:
        - |
          objectName: ${CERT_NAME}
          objectType: secret
    tenantId: "${TENANT_ID}"
  secretObjects:
  - secretName: tls-secret
    type: kubernetes.io/tls
    data:
    - objectName: ${CERT_NAME}
      key: tls.key
    - objectName: ${CERT_NAME}
      key: tls.crt