apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-vector-pvc
  namespace: otto
spec:
  storageClassName: managed-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-vector-deployment
  namespace: otto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-vector-db
  template:
    metadata:
      labels:
        app: postgres-vector-db
        tier: backend
    spec:
      containers:
        - name: postgres-vector-db
          image: pgvector/pgvector:pg16
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: vectordbpasswordkey
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: otto-configmap
                  key: VECTORDB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: otto-configmap
                  key: VECTORDB_USER
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-vector-volume-mount
              subPath: vectordb
              mountPath: /var/lib/postgresql/data
            - name: secrets
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: postgres-vector-volume-mount
          persistentVolumeClaim:
            claimName: postgres-vector-pvc
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-keyvault"

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-vector-service
  namespace: otto
spec:
  type: ClusterIP
  selector:
    app: postgres-vector-db
  ports:
  - port: 5432
    targetPort: 5432
