---
apiVersion: v1
kind: Namespace
metadata:
  name: velero

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero
  namespace: velero
  annotations:
    azure.workload.identity/client-id: ${VELERO_IDENTITY_CLIENT_ID}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero
subjects:
- kind: ServiceAccount
  name: velero
  namespace: velero
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-full-backup
  namespace: velero
spec:
  schedule: 0 1 * * * # Run at 1 AM daily
  template:
    csiSnapshotTimeout: 0s
    excludedNamespaces:
    - kube-system
    - velero
    includeClusterResources: true
    includedNamespaces:
    - '*'
    ttl: 720h # Retain backups for 30 days
  useOwnerReferencesInBackup: false

---

apiVersion: velero.io/v1
kind: Schedule
metadata:
  creationTimestamp: null
  name: hourly-incremental-postgres-backup
  namespace: velero
spec:
  schedule: 0 * * * * # Run every hour
  template:
    includedNamespaces:
    - otto
    includedResources:
    - persistentvolumeclaims
    - persistentvolumes
    snapshotVolumes: true
    storageLocation: default
    ttl: 48h # Retain backups for 2 days
  useOwnerReferencesInBackup: false

