# Generated by Django 5.1.8 on 2025-05-29 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(blank=True, max_length=255)),
                ("name_fr", models.CharField(blank=True, max_length=255)),
                ("description_en", models.TextField(blank=True)),
                ("description_fr", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sharing_option",
                    models.CharField(
                        choices=[
                            ("private", "Make private"),
                            ("everyone", "Share with everyone"),
                            ("others", "Share with others"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("template_html", models.TextField()),
                (
                    "accessible_to",
                    models.ManyToManyField(
                        related_name="accessible_templates", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
