# Generated by Django 5.0.7 on 2024-07-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("otto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(default="Untitled report", max_length=255)),
                ("wizard", models.CharField(max_length=255)),
                ("data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("access_controls", models.ManyToManyField(to="otto.accesscontrol")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
