# Generated by Django 5.1.8 on 2025-05-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="template",
            old_name="created_by",
            new_name="owner",
        ),
    ]
