# Generated by Django 5.1.8 on 2025-05-30 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0002_rename_created_by_template_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="example_source",
                        to="template_wizard.template",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                ("field_type", models.CharField(max_length=50)),
                ("required", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("prompt", models.TextField(blank=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="template_wizard.template",
                    ),
                ),
            ],
        ),
    ]
