# Generated by Django 5.1.8 on 2025-05-30 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0003_examplesource_templatefield"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "template",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="example_source",
                        to="template_wizard.template",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ExampleSource",
        ),
    ]
