# Generated by Django 5.1.8 on 2025-06-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0004_source_delete_examplesource"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatefield",
            name="list",
            field=models.BooleanField(
                default=False, help_text="Is this field a list of values?"
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("str", "Text"),
                    ("float", "Decimal"),
                    ("int", "Integer"),
                    ("bool", "Yes/No"),
                ],
                max_length=50,
            ),
        ),
    ]
