# Generated by Django 5.1.8 on 2025-06-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "template_wizard",
            "0004_source_extracted_json_source_template_result_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("extracting_text", "Extracting text"),
                    ("extracting_fields", "Extracting fields"),
                    ("filling_template", "Filling template"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
