# Generated by Django 5.1.8 on 2025-06-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0005_templatefield_list_alter_templatefield_field_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatefield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("str", "Text"),
                    ("float", "Decimal"),
                    ("int", "Integer"),
                    ("bool", "Yes/No"),
                ],
                default="str",
                max_length=50,
            ),
        ),
    ]
