# Generated by Django 5.1.8 on 2025-06-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0005_source_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="example_json_output",
        ),
        migrations.RemoveField(
            model_name="template",
            name="last_test_fields_result",
        ),
        migrations.RemoveField(
            model_name="template",
            name="last_test_layout_result",
        ),
        migrations.AlterField(
            model_name="source",
            name="extracted_json",
            field=models.JSONField(null=True),
        ),
    ]
