# Generated by Django 5.1.8 on 2025-06-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0003_rename_file_document_saved_file_document_file_path"),
        ("template_wizard", "0006_remove_template_example_json_output_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="templatesession",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveField(
            model_name="source",
            name="template",
        ),
        migrations.AddField(
            model_name="source",
            name="is_example_template",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="template",
            name="word_template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="librarian.savedfile",
            ),
        ),
        migrations.AddField(
            model_name="templatesession",
            name="example_session",
            field=models.BooleanField(
                default=False,
                help_text="Contains examples for use during template creation",
            ),
        ),
        migrations.AlterField(
            model_name="templatesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("select_sources", "Selecting"),
                    ("fill_template", "Processing"),
                    ("error", "Error"),
                    ("completed", "Completed"),
                ],
                default="select_sources",
                max_length=50,
            ),
        ),
    ]
