# Generated by Django 5.1.8 on 2025-06-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0006_alter_templatefield_field_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templatefield",
            name="prompt",
        ),
        migrations.AddField(
            model_name="templatefield",
            name="string_format",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("email", "Email"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("date-time", "Date and Time"),
                    ("duration", "Duration"),
                ],
                default="none",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("str", "Text"),
                    ("float", "Decimal"),
                    ("int", "Integer"),
                    ("bool", "Yes/No"),
                    ("object", "Object"),
                ],
                default="str",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="list",
            field=models.BooleanField(default=False),
        ),
    ]
