# Generated by Django 5.1.8 on 2025-06-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "template_wizard",
            "0007_alter_source_options_alter_templatesession_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="templatesession",
            old_name="example_session",
            new_name="is_example_session",
        ),
    ]
