# Generated by Django 5.1.8 on 2025-06-02 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0007_remove_templatefield_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatefield",
            name="parent_field",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_fields",
                to="template_wizard.templatefield",
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("str", "Text"),
                    ("float", "Decimal"),
                    ("int", "Integer"),
                    ("bool", "Yes/No"),
                    ("object", "Group of fields"),
                ],
                default="str",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="string_format",
            field=models.CharField(
                choices=[
                    ("none", "Free text"),
                    ("email", "Email"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("date-time", "Date and Time"),
                    ("duration", "Duration"),
                ],
                default="none",
                max_length=50,
            ),
        ),
    ]
