# Generated by Django 5.1.8 on 2025-06-12 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "template_wizard",
            "0008_rename_example_session_templatesession_is_example_session",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="last_example_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="template_wizard.source",
            ),
        ),
    ]
