# Generated by Django 5.1.8 on 2025-06-03 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0008_templatefield_parent_field_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="templatefield",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="template",
            name="example_json_output",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="generated_schema",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="template_html",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="template_wizard.template",
            ),
        ),
    ]
