# Generated by Django 5.1.8 on 2025-06-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0009_template_last_example_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="last_test_layout_type",
        ),
        migrations.RemoveField(
            model_name="template",
            name="layout_markdown",
        ),
        migrations.RemoveField(
            model_name="template",
            name="layout_type",
        ),
    ]
