# Generated by Django 5.1.8 on 2025-06-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0009_alter_templatefield_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatefield",
            name="slug",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for use in templates (letters, numbers, underscores only).",
                max_length=64,
                null=True,
            ),
        ),
    ]
