# Generated by Django 5.1.8 on 2025-06-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0010_remove_template_last_test_layout_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="fields_modified_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="layout_modified_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
