# Generated by Django 5.1.8 on 2025-06-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0011_template_fields_modified_timestamp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="template",
            old_name="word_template",
            new_name="docx_template",
        ),
    ]
