# Generated by Django 5.1.8 on 2025-06-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0011_populate_templatefield_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatefield",
            name="slug",
            field=models.CharField(
                default="ghfugh",
                help_text="Unique identifier for use in templates (letters, numbers, underscores only).",
                max_length=64,
            ),
            preserve_default=False,
        ),
    ]
