# Generated by Django 5.1.8 on 2025-06-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0012_rename_word_template_template_docx_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="docx_template_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
