# Generated by Django 5.1.8 on 2025-06-03 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0012_alter_templatefield_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatefield",
            name="parent_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_fields",
                to="template_wizard.templatefield",
            ),
        ),
    ]
