# Generated by Django 5.1.8 on 2025-06-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0013_template_docx_template_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatefield",
            name="slug",
            field=models.CharField(
                help_text="Unique identifier for use in templates (letters, numbers, underscores only).",
                max_length=256,
            ),
        ),
    ]
