# Generated by Django 5.1.8 on 2025-06-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0013_alter_templatefield_parent_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="template_html",
        ),
        migrations.AddField(
            model_name="template",
            name="layout_string",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="layout_type",
            field=models.CharField(
                choices=[
                    ("llm_generation", "LLM Generation"),
                    ("markdown_substitution", "Markdown with Substitution"),
                    ("jinja_rendering", "Jinja Rendering"),
                ],
                default="llm_generation",
                max_length=50,
            ),
        ),
    ]
