# Generated by Django 5.1.8 on 2025-06-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "template_wizard",
            "0014_remove_template_template_html_template_layout_string_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="template",
            old_name="layout_string",
            new_name="layout_jinja",
        ),
        migrations.AddField(
            model_name="template",
            name="layout_markdown",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="layout_type",
            field=models.CharField(
                choices=[
                    ("llm_generation", "LLM Generation"),
                    ("markdown_substitution", "Markdown with Substitution"),
                    ("jinja_rendering", "Jinja Rendering"),
                    ("word_template", "Word Template"),
                ],
                default="llm_generation",
                max_length=50,
            ),
        ),
    ]
