# Generated by Django 5.1.8 on 2025-06-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template_wizard", "0014_alter_templatefield_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="pdf_method",
            field=models.CharField(
                choices=[
                    ("default", "text only"),
                    ("azure_read", "OCR"),
                    ("azure_layout", "layout & OCR"),
                ],
                default="default",
                max_length=50,
            ),
        ),
    ]
