# Generated by Django 5.1.8 on 2025-06-17 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0003_rename_file_document_saved_file_document_file_path"),
        ("template_wizard", "0016_remove_source_pdf_method_templatesession_pdf_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="docx_template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="docx_templates",
                to="librarian.savedfile",
            ),
        ),
    ]
