# Generated by Django 5.1.5 on 2025-02-12 16:23

import django.db.models.deletion
import librarian.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid_hex",
                    models.CharField(
                        default=librarian.models.generate_uuid_hex,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Not started"),
                            ("INIT", "Starting..."),
                            ("PROCESSING", "Processing..."),
                            ("SUCCESS", "Success"),
                            ("ERROR", "Error"),
                            ("BLOCKED", "Stopped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("status_details", models.TextField(blank=True, null=True)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "usd_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "extracted_title",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("extracted_modified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_title",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("generated_description", models.TextField(blank=True, null=True)),
                (
                    "manual_title",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("extracted_text", models.TextField(blank=True, null=True)),
                ("num_chunks", models.IntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("selector", models.CharField(blank=True, max_length=255, null=True)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "url_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("filename", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "pdf_extraction_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("default", "text only"),
                            ("azure_read", "OCR"),
                            ("azure_layout", "layout & OCR"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid_hex",
                    models.CharField(
                        default=librarian.models.generate_uuid_hex,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                ("name_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.IntegerField(default=0)),
                ("is_public", models.BooleanField(default=False)),
                ("is_default_library", models.BooleanField(default=False)),
                ("is_personal_library", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Libraries",
                "ordering": [
                    "-is_personal_library",
                    "-is_public",
                    "order",
                    "-created_at",
                ],
            },
        ),
        migrations.CreateModel(
            name="LibraryUserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("contributor", "Contributor"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sha256_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("file", models.FileField(max_length=500, upload_to="files/%Y/%m/%d/")),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("eof", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid_hex",
                    models.CharField(
                        default=librarian.models.generate_uuid_hex,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_fr", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "chat",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_source",
                        to="chat.chat",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
