# Generated by Django 5.1.6 on 2025-04-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedfile",
            name="nested_file_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
