# Generated by Django 5.1.6 on 2025-04-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0003_savedfile_nested_file_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedfile",
            name="nested_file_path",
        ),
        migrations.AddField(
            model_name="document",
            name="filepath",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
