# Generated by Django 5.1.8 on 2025-08-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0003_rename_file_document_saved_file_document_file_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="pdf_extraction_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "text only"),
                    ("layout", "text & layout"),
                    ("azure_read", "OCR"),
                    ("azure_layout", "OCR & layout"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
