# Generated by Django 5.1 on 2024-08-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0003_library_is_default_library"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="cost",
            field=models.DecimalField(decimal_places=6, max_digits=10, default=0),
        ),
    ]
