# Generated by Django 5.1.8 on 2025-08-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0003_rename_file_document_saved_file_document_file_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasource",
            name="security_label",
        ),
    ]
