# Generated by Django 5.1.8 on 2025-09-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0004_alter_document_pdf_extraction_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedfile",
            name="filename",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
