# Generated by Django 5.1.8 on 2025-09-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0005_add_filename_to_savedfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedfile",
            name="filename",
        ),
    ]
