# Generated by Django 5.1 on 2024-09-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0005_rename_cost_document_usd_cost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="library",
            options={
                "ordering": ["-is_personal_library", "-is_public", "order", "name"],
                "verbose_name_plural": "Libraries",
            },
        ),
        migrations.AddField(
            model_name="library",
            name="is_personal_library",
            field=models.BooleanField(default=False),
        ),
    ]
