# Generated by Django 5.1 on 2024-09-19 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_chatoptions_qa_documents_chatoptions_qa_scope"),
        ("librarian", "0006_alter_library_options_library_is_personal_library"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="library",
            name="chat",
        ),
        migrations.AddField(
            model_name="datasource",
            name="chat",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_source",
                to="chat.chat",
            ),
        ),
    ]
