# Generated by Django 5.2.5 on 2025-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0006_remove_filename_from_savedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="azure_content_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="azure_operation_location",
            field=models.URLField(blank=True, null=True),
        ),
    ]
