# Generated by Django 5.2.5 on 2025-10-06 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0007_document_azure_content_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="librarian.datasource",
            ),
        ),
    ]
