# Generated by Django 5.1 on 2024-10-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0022_remove_chat_data_source_remove_chat_options_and_more"),
        ("librarian", "0008_remove_datasource_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="chat",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_source",
                to="chat.chat",
            ),
        ),
    ]
