# Generated by Django 5.2.5 on 2025-10-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0008_alter_document_data_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="azure_content_hash",
        ),
        migrations.RemoveField(
            model_name="document",
            name="azure_operation_location",
        ),
        migrations.RemoveField(
            model_name="document",
            name="celery_task_id",
        ),
    ]
