# Generated by Django 5.1 on 2024-10-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0009_datasource_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="pdf_extraction_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "text only"),
                    ("azure_read", "OCR"),
                    ("azure_layout", "layout & OCR"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
