# Generated by Django 5.1 on 2024-10-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0009_datasource_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="pdf_crop_bottom",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_crop_left",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_crop_right",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_crop_top",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_extraction_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Otto default (text only)"),
                    ("azure_ocr", "Azure Read (OCR)"),
                    ("azure_layout", "Azure Layout (OCR + tables)"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_num_pages_detected",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_num_pages_extracted",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_page_range",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
