# Generated by Django 5.2.5 on 2025-10-10 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0028_remove_chatfile_text"),
        ("librarian", "0009_remove_document_azure_content_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="chat.message",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Not started"),
                    ("INIT", "Starting..."),
                    ("PROCESSING", "Processing..."),
                    ("TEXT_EXTRACTED", "Text extracted"),
                    ("SUCCESS", "Success"),
                    ("ERROR", "Error"),
                    ("BLOCKED", "Stopped"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
