# Generated by Django 5.1 on 2024-10-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0010_document_pdf_extraction_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="pdf_crop_bottom",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_crop_left",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_crop_right",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_crop_top",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_num_pages_detected",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_num_pages_extracted",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="pdf_page_range",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
