# Generated by Django 5.1 on 2024-10-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0010_document_pdf_crop_bottom_document_pdf_crop_left_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="pdf_extraction_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "text only"),
                    ("azure_read", "OCR"),
                    ("azure_layout", "layout & OCR"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
