# Generated by Django 5.1.1 on 2024-11-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0010_document_pdf_extraction_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datasource",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="library",
            options={
                "ordering": [
                    "-is_personal_library",
                    "-is_public",
                    "order",
                    "-created_at",
                ],
                "verbose_name_plural": "Libraries",
            },
        ),
    ]
