# Generated by Django 5.2.5 on 2025-10-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0028_remove_chatfile_text"),
        ("librarian", "0010_document_message_alter_document_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="message",
        ),
        migrations.AddField(
            model_name="document",
            name="messages",
            field=models.ManyToManyField(
                blank=True, related_name="attached_documents", to="chat.message"
            ),
        ),
    ]
