# Generated by Django 5.1.1 on 2024-11-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0011_alter_datasource_options_alter_library_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="sha256_hash",
        ),
    ]
