# Generated by Django 5.2.5 on 2025-10-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0011_remove_document_message_document_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_container",
            field=models.BooleanField(default=False),
        ),
    ]
