# Generated by Django 5.1.1 on 2024-11-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0012_remove_document_sha256_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="status_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
