# Generated by Django 5.2.5 on 2025-10-15 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0012_add_is_container_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="parent_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_documents",
                to="librarian.document",
            ),
        ),
    ]
