# Generated by Django 5.2.7 on 2025-10-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0013_add_parent_document_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="hnsw_enabled",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="None=automatic, True=force on, False=force off",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="library",
            name="hnsw_status",
            field=models.CharField(
                choices=[
                    ("none", "No index"),
                    ("pending", "Build pending"),
                    ("building", "Building index"),
                    ("ready", "Index ready"),
                    ("error", "Build failed"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="library",
            name="hnsw_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="library",
            name="total_chunks",
            field=models.IntegerField(default=0),
        ),
    ]
