# Generated by Django 5.1.1 on 2024-11-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0014_alter_libraryuserrole_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="extracted_title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="filename",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="generated_title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="manual_title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="savedfile",
            name="file",
            field=models.FileField(max_length=500, upload_to="files/%Y/%m/%d/"),
        ),
    ]
