# Generated by Django 5.2.7 on 2025-10-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0014_library_hnsw_enabled_library_hnsw_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="hnsw_status",
            field=models.CharField(
                choices=[
                    ("none", "No index"),
                    ("pending", "Build pending"),
                    ("building", "Building index"),
                    ("ready", "Index ready"),
                    ("deleting", "Deleting index"),
                    ("error", "Build failed"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
