# Generated by Django 5.2.8 on 2025-11-10 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0030_chat_chat_chat_user_id_4f3805_idx_and_more"),
        ("librarian", "0015_alter_library_hnsw_status"),
        ("otto", "0009_feedback_otto_feedba_status_2f94bd_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["order", "-created_at"], name="librarian_d_order_97bb87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["-created_at"], name="librarian_d_created_440997_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["data_source", "status"], name="librarian_d_data_so_494e0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["data_source", "is_container"],
                name="librarian_d_data_so_ce4df8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["data_source", "-created_at"],
                name="librarian_d_data_so_aa9d80_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["data_source", "-extracted_modified_at", "-created_at"],
                name="librarian_d_data_so_58a85c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["data_source", "filename"],
                name="librarian_d_data_so_9fa937_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["data_source", "num_chunks"],
                name="librarian_d_data_so_abd203_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="library",
            index=models.Index(
                fields=["-is_personal_library", "-is_public", "order", "-created_at"],
                name="librarian_l_is_pers_2cca83_idx",
            ),
        ),
    ]
