# Generated by Django 5.2.9 on 2026-01-12 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0001_initial"),
        ("librarian", "0016_datasource_librarian_d_order_97bb87_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="chat_next",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_source",
                to="chat_next.chat",
            ),
        ),
    ]
