# Generated by Django 5.2.9 on 2026-01-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0001_initial"),
        ("librarian", "0017_datasource_chat_next"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="chat_next_messages",
            field=models.ManyToManyField(
                blank=True, related_name="attached_documents", to="chat_next.message"
            ),
        ),
    ]
