# Generated by Django 5.2.9 on 2026-01-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0018_document_chat_next_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedfile",
            name="openai_file_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
