# Generated by Django 6.0.3 on 2026-03-31 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0020_alter_chatsettings_send_name_to_model_default"),
        ("librarian", "0019_add_openai_file_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="library",
            options={
                "ordering": [
                    "-is_personal_library",
                    "-is_skill_library",
                    "-is_public",
                    "order",
                    "-created_at",
                ],
                "verbose_name_plural": "Libraries",
            },
        ),
        migrations.RemoveIndex(
            model_name="library",
            name="librarian_l_is_pers_2cca83_idx",
        ),
        migrations.AddField(
            model_name="datasource",
            name="skill",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_source",
                to="chat_next.skill",
            ),
        ),
        migrations.AddField(
            model_name="library",
            name="is_skill_library",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="library",
            index=models.Index(
                fields=[
                    "-is_personal_library",
                    "-is_skill_library",
                    "-is_public",
                    "order",
                    "-created_at",
                ],
                name="librarian_l_is_pers_53f7ca_idx",
            ),
        ),
    ]
