# Generated by Django 6.0.3 on 2026-03-31 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0020_alter_library_options_and_more"),
        ("otto", "0023_team_teammembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryTeamRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("contributor", "Contributor"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_roles",
                        to="librarian.library",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_roles",
                        to="otto.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("library", "team")},
            },
        ),
    ]
