# Generated by Django 6.0.4 on 2026-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0022_document_provenance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Not started"),
                    ("INIT", "Starting..."),
                    ("PROCESSING", "Processing..."),
                    ("TEXT_EXTRACTED", "Text extracted"),
                    ("PAUSED", "Paused"),
                    ("SUCCESS", "Success"),
                    ("ERROR", "Error"),
                    ("BLOCKED", "Stopped"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
