# Generated by Django 6.0.5 on 2026-05-28 19:52

import django.db.models.deletion
from django.db import migrations, models


def backfill_document_original_file_fields(apps, schema_editor):
    Document = apps.get_model("librarian", "Document")

    Document.objects.filter(
        original_saved_file__isnull=True,
        saved_file__isnull=False,
    ).update(original_saved_file=models.F("saved_file"))

    Document.objects.filter(
        original_filename__isnull=True,
    ).exclude(filename__isnull=True).update(original_filename=models.F("filename"))


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("librarian", "0023_alter_document_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="original_filename",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="original_saved_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="original_documents",
                to="librarian.savedfile",
            ),
        ),
        migrations.CreateModel(
            name="SavedFileDerivative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("derivation_type", models.CharField(db_index=True, max_length=64)),
                ("derivation_version", models.CharField(default="1", max_length=32)),
                ("derivation_params", models.JSONField(blank=True, default=dict)),
                (
                    "cache_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "derived_saved_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_derivatives",
                        to="librarian.savedfile",
                    ),
                ),
                (
                    "source_saved_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_files",
                        to="librarian.savedfile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_saved_file", "derivation_type"],
                        name="librarian_s_source__effaf2_idx",
                    ),
                    models.Index(
                        fields=["derived_saved_file"],
                        name="librarian_s_derived_92c4a7_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            backfill_document_original_file_fields,
            migrations.RunPython.noop,
        ),
    ]
