# Generated by Django 6.0.5 on 2026-06-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("librarian", "0024_document_original_filename_and_more"),
        ("librarian", "0024_library_deleted_at"),
    ]

    operations = []
