# Generated by Django 5.1 on 2024-10-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=255)),
                ("receiver", models.CharField(max_length=255)),
                ("sent_date", models.DateTimeField()),
                ("file", models.FileField(upload_to="emails/")),
            ],
        ),
    ]
