# Generated by Django 5.1 on 2024-11-12 14:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chronology_email", "0002_email_preview_context"),
    ]

    operations = [
        migrations.RenameField(
            model_name="email",
            old_name="preview_context",
            new_name="preview_text",
        ),
        migrations.AddField(
            model_name="email",
            name="thread_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
