# Generated by Django 5.1 on 2024-11-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chronology_email", "0003_rename_preview_context_email_preview_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
