# Generated by Django 5.1 on 2024-11-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chronology_email", "0005_alter_email_file_alter_email_sent_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="attachment_count",
            field=models.IntegerField(default=0),
        ),
    ]
