# Generated by Django 5.1.1 on 2024-12-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chronology_email", "0006_email_attachment_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
