# Generated by Django 5.1.1 on 2024-12-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chronology_email", "0007_email_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="unique_participants",
            field=models.IntegerField(default=0),
        ),
    ]
