apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-django-pv
  namespace: otto  
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
spec:
  storageClassName: managed-csi
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: disk.csi.azure.com
    volumeHandle: /subscriptions/86ca3d9f-ad5e-4c04-8dea-af9a9802e459/resourceGroups/MC_OttoADEVRg_jus-dev-ottoa-aks_canadacentral/providers/Microsoft.Compute/disks/jus-dev-ottoa-disk
    volumeAttributes:
      fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-django-pvc
  namespace: otto
spec:
  storageClassName: managed-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi    
  volumeName: postgres-django-pv


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-django-deployment
  namespace: otto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-django-db
  template:
    metadata:
      labels:
        app: postgres-django-db
        tier: backend
    spec:
      containers:
        - name: postgres-django-db
          image: pgvector/pgvector:pg16
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: azure-keyvault-secrets
                  key: postgrespasswordkey
            - name: POSTGRES_DB
              value: "otto"
            - name: POSTGRES_USER
              value: "postgres"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-django-volume-mount
              subPath: vectordb
              mountPath: /var/lib/postgresql/data
            - name: secrets
              mountPath: "/mnt/secrets-store"
              readOnly: true   
      volumes:
        - name: postgres-django-volume-mount
          persistentVolumeClaim:
            claimName: postgres-django-pvc
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-keyvault"
---

apiVersion: v1
kind: Service
metadata:
  name: postgres-django-service
  namespace: otto
spec:
  type: ClusterIP
  selector:
    app: postgres-django-db
  ports:
  - port: 5432
    targetPort: 5432
