apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
spec:
  containers:
  - name: privileged-container
    image: ubuntu
    command: ["/bin/bash", "-c", "sleep infinity"]
    securityContext:
      privileged: true
    volumeMounts:
      - name: postgres-django-volume-mount
        mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-django-volume-mount
      persistentVolumeClaim:
        claimName: postgres-django-pvc
