apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "137"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"128"},"creationTimestamp":"2024-10-10T16:53:35Z","generation":163,"name":"django-deployment","namespace":"otto","resourceVersion":"85177345","uid":"c4c116fd-710c-4464-b53a-7a142865b4a9"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"django-app"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2025-05-12T14:29:04Z"},"creationTimestamp":null,"labels":{"app":"django-app"}},"spec":{"containers":[{"env":[{"name":"DJANGO_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"djangosecretkey","name":"azure-keyvault-secrets"}}},{"name":"DJANGODB_HOST","valueFrom":{"secretKeyRef":{"key":"djangodbhostkey","name":"azure-keyvault-secrets"}}},{"name":"DJANGODB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"djangodbpasswordkey","name":"azure-keyvault-secrets"}}},{"name":"VECTORDB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"vectordbpasswordkey","name":"azure-keyvault-secrets"}}},{"name":"AZURE_OPENAI_KEY","valueFrom":{"secretKeyRef":{"key":"openaiservicekey","name":"azure-keyvault-secrets"}}},{"name":"AZURE_COGNITIVE_SERVICE_KEY","valueFrom":{"secretKeyRef":{"key":"cognitiveservicekey","name":"azure-keyvault-secrets"}}},{"name":"AZURE_ACCOUNT_KEY","valueFrom":{"secretKeyRef":{"key":"storageaccountkey","name":"azure-keyvault-secrets"}}},{"name":"ENTRA_CLIENT_SECRET","valueFrom":{"secretKeyRef":{"key":"entraclientsecretkey","name":"azure-keyvault-secrets"}}},{"name":"AZURE_OPENAI_CANADA_CENTRAL_KEY","valueFrom":{"secretKeyRef":{"key":"openaicanadacentralkey","name":"azure-keyvault-secrets"}}}],"envFrom":[{"configMapRef":{"name":"otto-configmap"}}],"image":"jussandboxottoacr.azurecr.io/otto:latest","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":5,"httpGet":{"httpHeaders":[{"name":"Host","value":"django-service"}],"path":"/healthz/","port":8000,"scheme":"HTTP"},"initialDelaySeconds":30,"periodSeconds":20,"successThreshold":1,"timeoutSeconds":10},"name":"django-app-container","ports":[{"containerPort":8000,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"httpHeaders":[{"name":"Host","value":"django-service"}],"path":"/healthz/","port":8000,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":15,"successThreshold":1,"timeoutSeconds":10},"resources":{"limits":{"memory":"8Gi"},"requests":{"cpu":"1","memory":"3Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/mnt/secrets-store","name":"secrets","readOnly":true},{"mountPath":"/data/static","name":"staticfiles-pv-storage"},{"mountPath":"/data/media","name":"media-pv-storage"}]}],"dnsPolicy":"ClusterFirst","initContainers":[{"command":["sh","-c","echo 'Starting collectstatic'; python manage.py collectstatic --noinput; echo 'Collectstatic completed'; echo 'Starting migrate'; python manage.py migrate --noinput; echo 'Migrate completed'"],"env":[{"name":"DJANGO_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"djangosecretkey","name":"azure-keyvault-secrets"}}},{"name":"DJANGODB_HOST","valueFrom":{"secretKeyRef":{"key":"djangodbhostkey","name":"azure-keyvault-secrets"}}},{"name":"DJANGODB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"djangodbpasswordkey","name":"azure-keyvault-secrets"}}},{"name":"VECTORDB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"vectordbpasswordkey","name":"azure-keyvault-secrets"}}},{"name":"AZURE_OPENAI_KEY","valueFrom":{"secretKeyRef":{"key":"openaiservicekey","name":"azure-keyvault-secrets"}}},{"name":"AZURE_COGNITIVE_SERVICE_KEY","valueFrom":{"secretKeyRef":{"key":"cognitiveservicekey","name":"azure-keyvault-secrets"}}},{"name":"AZURE_ACCOUNT_KEY","valueFrom":{"secretKeyRef":{"key":"storageaccountkey","name":"azure-keyvault-secrets"}}},{"name":"ENTRA_CLIENT_SECRET","valueFrom":{"secretKeyRef":{"key":"entraclientsecretkey","name":"azure-keyvault-secrets"}}},{"name":"AZURE_OPENAI_CANADA_CENTRAL_KEY","valueFrom":{"secretKeyRef":{"key":"openaicanadacentralkey","name":"azure-keyvault-secrets"}}}],"envFrom":[{"configMapRef":{"name":"otto-configmap"}}],"image":"jussandboxottoacr.azurecr.io/otto:latest","imagePullPolicy":"Always","name":"init-migrate-collectstatic","resources":{"limits":{"cpu":"1","memory":"4Gi"},"requests":{"cpu":"1","memory":"3Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/mnt/secrets-store","name":"secrets","readOnly":true},{"mountPath":"/data/static","name":"staticfiles-pv-storage"},{"mountPath":"/data/media","name":"media-pv-storage"}]}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"csi":{"driver":"secrets-store.csi.k8s.io","readOnly":true,"volumeAttributes":{"secretProviderClass":"azure-keyvault"}},"name":"secrets"},{"name":"staticfiles-pv-storage","persistentVolumeClaim":{"claimName":"staticfiles-pvc"}},{"name":"media-pv-storage","persistentVolumeClaim":{"claimName":"media-pvc"}}]}}},"status":{"availableReplicas":2,"conditions":[{"lastTransitionTime":"2025-05-06T17:04:43Z","lastUpdateTime":"2025-05-06T17:04:43Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2025-03-05T12:57:14Z","lastUpdateTime":"2025-05-12T14:31:55Z","message":"ReplicaSet \"django-deployment-586fc98864\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":163,"readyReplicas":2,"replicas":2,"updatedReplicas":2}}
  creationTimestamp: "2024-10-10T16:53:35Z"
  generation: 173
  name: django-deployment
  namespace: otto
  resourceVersion: "92553613"
  uid: c4c116fd-710c-4464-b53a-7a142865b4a9
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: django-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-05-28T17:25:47Z"
      creationTimestamp: null
      labels:
        app: django-app
    spec:
      containers:
      - env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: djangosecretkey
              name: azure-keyvault-secrets
        - name: DJANGODB_HOST
          valueFrom:
            secretKeyRef:
              key: djangodbhostkey
              name: azure-keyvault-secrets
        - name: DJANGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: djangodbpasswordkey
              name: azure-keyvault-secrets
        - name: VECTORDB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: vectordbpasswordkey
              name: azure-keyvault-secrets
        - name: AZURE_OPENAI_KEY
          valueFrom:
            secretKeyRef:
              key: openaiservicekey
              name: azure-keyvault-secrets
        - name: AZURE_COGNITIVE_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              key: cognitiveservicekey
              name: azure-keyvault-secrets
        - name: AZURE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              key: storageaccountkey
              name: azure-keyvault-secrets
        - name: ENTRA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: entraclientsecretkey
              name: azure-keyvault-secrets
        - name: AZURE_OPENAI_CANADA_CENTRAL_KEY
          valueFrom:
            secretKeyRef:
              key: openaicanadacentralkey
              name: azure-keyvault-secrets
        envFrom:
        - configMapRef:
            name: otto-configmap
        image: jussandboxottoacr.azurecr.io/otto:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            httpHeaders:
            - name: Host
              value: django-service
            path: /healthz/
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        name: django-app-container
        ports:
        - containerPort: 8000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: django-service
            path: /healthz/
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 3Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/secrets-store
          name: secrets
          readOnly: true
        - mountPath: /data/static
          name: staticfiles-pv-storage
        - mountPath: /data/media
          name: media-pv-storage
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - echo 'Starting collectstatic'; python manage.py collectstatic --noinput;
          echo 'Collectstatic completed'; echo 'Starting migrate'; python manage.py
          migrate --noinput; echo 'Migrate completed'
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: djangosecretkey
              name: azure-keyvault-secrets
        - name: DJANGODB_HOST
          valueFrom:
            secretKeyRef:
              key: djangodbhostkey
              name: azure-keyvault-secrets
        - name: DJANGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: djangodbpasswordkey
              name: azure-keyvault-secrets
        - name: VECTORDB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: vectordbpasswordkey
              name: azure-keyvault-secrets
        - name: AZURE_OPENAI_KEY
          valueFrom:
            secretKeyRef:
              key: openaiservicekey
              name: azure-keyvault-secrets
        - name: AZURE_COGNITIVE_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              key: cognitiveservicekey
              name: azure-keyvault-secrets
        - name: AZURE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              key: storageaccountkey
              name: azure-keyvault-secrets
        - name: ENTRA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: entraclientsecretkey
              name: azure-keyvault-secrets
        - name: AZURE_OPENAI_CANADA_CENTRAL_KEY
          valueFrom:
            secretKeyRef:
              key: openaicanadacentralkey
              name: azure-keyvault-secrets
        envFrom:
        - configMapRef:
            name: otto-configmap
        image: jussandboxottoacr.azurecr.io/otto:latest
        imagePullPolicy: Always
        name: init-migrate-collectstatic
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 3Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/secrets-store
          name: secrets
          readOnly: true
        - mountPath: /data/static
          name: staticfiles-pv-storage
        - mountPath: /data/media
          name: media-pv-storage
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-keyvault
        name: secrets
      - name: staticfiles-pv-storage
        persistentVolumeClaim:
          claimName: staticfiles-pvc
      - name: media-pv-storage
        persistentVolumeClaim:
          claimName: media-pvc
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-05-26T20:08:04Z"
    lastUpdateTime: "2025-05-26T20:08:04Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-03-05T12:57:14Z"
    lastUpdateTime: "2025-05-28T17:27:53Z"
    message: ReplicaSet "django-deployment-67d4b78b4f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 173
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
