apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"django-service","namespace":"otto"},"spec":{"ports":[{"port":80,"targetPort":8000}],"selector":{"app":"django-app"},"type":"ClusterIP"}}
  creationTimestamp: "2024-10-10T16:53:35Z"
  name: django-service
  namespace: otto
  resourceVersion: "325125"
  uid: 0c5f8461-c826-4999-8d90-1cbaa7590130
spec:
  clusterIP: 10.0.239.234
  clusterIPs:
  - 10.0.239.234
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: django-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
