# Generated by Django 5.1.5 on 2025-02-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Law",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("title_en", models.TextField(null=True)),
                ("title_fr", models.TextField(null=True)),
                ("short_title", models.TextField(blank=True, null=True)),
                ("short_title_en", models.TextField(blank=True, null=True)),
                ("short_title_fr", models.TextField(blank=True, null=True)),
                ("long_title", models.TextField(blank=True, null=True)),
                ("long_title_en", models.TextField(blank=True, null=True)),
                ("long_title_fr", models.TextField(blank=True, null=True)),
                ("ref_number", models.CharField(max_length=255)),
                ("ref_number_en", models.CharField(max_length=255, null=True)),
                ("ref_number_fr", models.CharField(max_length=255, null=True)),
                (
                    "enabling_authority",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "enabling_authority_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "enabling_authority_fr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("node_id", models.CharField(max_length=255, unique=True)),
                (
                    "node_id_en",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                (
                    "node_id_fr",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                (
                    "sha_256_hash_en",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "sha_256_hash_fr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("type", models.CharField(default="act", max_length=255)),
                ("last_amended_date", models.DateField(blank=True, null=True)),
                ("current_date", models.DateField(blank=True, null=True)),
                ("in_force_start_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
