# Generated by Django 5.0.7 on 2024-07-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Law",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("short_title", models.TextField(blank=True, null=True)),
                ("long_title", models.TextField(blank=True, null=True)),
                ("ref_number", models.CharField(max_length=255)),
                ("law_id", models.CharField(max_length=255)),
                ("lang", models.CharField(default="eng", max_length=10)),
                ("type", models.CharField(default="act", max_length=255)),
                ("last_amended_date", models.DateField(null=True)),
                ("current_date", models.DateField(null=True)),
                (
                    "enabling_authority",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("node_id", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
