# Generated by Django 5.1 on 2024-09-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="law",
            name="lang",
        ),
        migrations.RemoveField(
            model_name="law",
            name="law_id",
        ),
        migrations.AddField(
            model_name="law",
            name="in_force_start_date",
            field=models.DateField(null=True),
        ),
    ]
