# Generated by Django 5.1.8 on 2025-06-26 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0002_law_laws_law_title_797cd1_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="law",
            name="checked_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
