# Generated by Django 5.1 on 2024-09-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0002_remove_law_lang_remove_law_law_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="law",
            name="enabling_authority_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="law",
            name="enabling_authority_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="law",
            name="long_title_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="law",
            name="long_title_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="law",
            name="node_id_en",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="law",
            name="node_id_fr",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="law",
            name="ref_number_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="law",
            name="ref_number_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="law",
            name="short_title_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="law",
            name="short_title_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="law",
            name="title_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="law",
            name="title_fr",
            field=models.TextField(null=True),
        ),
    ]
