# Generated by Django 5.1.8 on 2025-06-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0003_law_checked_date"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="law",
            index=models.Index(fields=["node_id"], name="laws_law_node_id_5e003a_idx"),
        ),
    ]
