# Generated by Django 5.1 on 2024-09-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0003_law_enabling_authority_en_law_enabling_authority_fr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="law",
            name="current_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="law",
            name="in_force_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="law",
            name="last_amended_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
