# Generated by Django 5.1 on 2024-09-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0004_alter_law_current_date_alter_law_in_force_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="law",
            name="title",
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name="law",
            name="title_en",
            field=models.CharField(max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name="law",
            name="title_fr",
            field=models.CharField(max_length=511, null=True),
        ),
    ]
