# Generated by Django 5.1.8 on 2025-07-02 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0004_law_laws_law_node_id_5e003a_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="in_progress", max_length=50)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("purged_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="law",
            name="checked_date",
        ),
        migrations.AddField(
            model_name="law",
            name="eng_law_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="LawLoadingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eng_law_id", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.CharField(default="pending", max_length=50)),
                ("details", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("cost", models.FloatField(default=0.0)),
                (
                    "sha_256_hash_en",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "sha_256_hash_fr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "law",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loading_status",
                        to="laws.law",
                    ),
                ),
            ],
        ),
    ]
