# Generated by Django 5.1 on 2024-09-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0005_alter_law_title_alter_law_title_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="law",
            name="long_title",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name="law",
            name="long_title_en",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name="law",
            name="long_title_fr",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name="law",
            name="short_title",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name="law",
            name="short_title_en",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name="law",
            name="short_title_fr",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
