# Generated by Django 5.1.8 on 2025-07-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0005_jobstatus_remove_law_checked_date_law_eng_law_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobstatus",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
