# Generated by Django 5.1.8 on 2025-07-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0006_jobstatus_celery_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobstatus",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
