# Generated by Django 5.1 on 2024-09-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0006_alter_law_long_title_alter_law_long_title_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="law",
            name="long_title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="law",
            name="long_title_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="law",
            name="long_title_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="law",
            name="short_title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="law",
            name="short_title_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="law",
            name="short_title_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="law",
            name="title",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="law",
            name="title_en",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="law",
            name="title_fr",
            field=models.TextField(null=True),
        ),
    ]
