# Generated by Django 5.1 on 2024-09-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0007_alter_law_long_title_alter_law_long_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="law",
            name="sha_256_hash_en",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="law",
            name="sha_256_hash_fr",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
