# Generated by Django 5.1.8 on 2025-07-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0007_alter_jobstatus_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobstatus",
            name="status",
            field=models.CharField(blank=True, default="not_started", max_length=50),
        ),
    ]
