# Generated by Django 5.1.8 on 2025-07-04 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0008_alter_jobstatus_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobstatus",
            name="purged_count",
        ),
        migrations.AlterField(
            model_name="lawloadingstatus",
            name="law",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loading_status",
                to="laws.law",
            ),
        ),
    ]
