# Generated by Django 5.1.8 on 2025-07-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0009_remove_jobstatus_purged_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawloadingstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_new", "Pending (New)"),
                    ("pending_update", "Pending (Update)"),
                    ("finished_new", "Finished (New)"),
                    ("finished_update", "Finished (Update)"),
                    ("finished_nochange", "Finished (No Change)"),
                    ("error", "Error"),
                    ("deleted", "Deleted"),
                    ("empty", "Empty"),
                ],
                default="pending_new",
                max_length=50,
            ),
        ),
    ]
