# Generated by Django 5.1.8 on 2025-07-04 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0010_alter_lawloadingstatus_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawloadingstatus",
            name="law",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loading_status",
                to="laws.law",
            ),
        ),
    ]
