# Generated by Django 5.1.8 on 2025-07-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0011_alter_lawloadingstatus_law"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawloadingstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_new", "Pending (New)"),
                    ("pending_update", "Pending (Update)"),
                    ("parsing_xml", "Parsing XML"),
                    ("embedding_nodes", "Embedding Nodes"),
                    ("finished_new", "Finished (New)"),
                    ("finished_update", "Finished (Update)"),
                    ("finished_nochange", "Finished (No Change)"),
                    ("error", "Error"),
                    ("deleted", "Deleted"),
                    ("empty", "Empty"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending_new",
                max_length=50,
            ),
        ),
    ]
