# Generated by Django 5.1.8 on 2025-08-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0012_alter_lawloadingstatus_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobstatus",
            name="options",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
