# Generated by Django 5.1.8 on 2025-08-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0014_lawsearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawsearch",
            name="query_uuid",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
