# Generated by Django 5.2.5 on 2025-09-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0015_lawsearch_query_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobstatus",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cancelled", "Cancelled"),
                    ("started", "Started"),
                    ("downloading", "Downloading"),
                    ("resetting", "Resetting"),
                    ("purging", "Purging"),
                    ("checking_existing", "Checking Existing"),
                    ("generating_hashes", "Generating Hashes"),
                    ("loading_laws", "Loading Laws"),
                    ("rebuilding_indexes", "Rebuilding Indexes"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                    ("not_started", "Not started"),
                    ("error", "Error"),
                ],
                default="not_started",
                max_length=50,
            ),
        ),
    ]
