# Generated by Django 5.2.7 on 2025-11-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0016_alter_jobstatus_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="law",
            name="eng_law_id",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
