"""
Django settings for otto project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import logging
import os
import sys
from pathlib import Path
from urllib.parse import urlparse, urlunparse

import structlog
import yaml
from dotenv import load_dotenv
from storages.backends.azure_storage import AzureStorage

from otto import priorities

from chat._llm.models import (
    DEFAULT_CHAT_MODEL_ID,
    DEFAULT_LAWS_MODEL_ID,
    DEFAULT_QA_MODEL_ID,
    DEFAULT_SUMMARIZE_MODEL_ID,
    DEFAULT_TRANSLATE_MODEL_ID,
)

from .utils import logging as logging_utils

BASE_DIR = Path(__file__).resolve().parent.parent

# Set the logging level for all azure-* libraries
logger = logging.getLogger("azure.identity")
logger.setLevel(logging.ERROR)

OTTO_BUILD_DATE = ""
OTTO_VERSION_HASH = ""
OTTO_USER_GROUP = "Otto user"
OTTO_ADMIN_GROUP = "Otto admin"
OTTO_OPERATIONS_ADMIN_GROUP = "Operations admin"
OTTO_BULK_UPLOADER_GROUP = "Bulk uploader"
# Backward-compatible alias; prefer OTTO_BULK_UPLOADER_GROUP in new code.
OTTO_DATA_STEWARD_GROUP = OTTO_BULK_UPLOADER_GROUP
OTTO_PUBLIC_SHARING_ADMIN_GROUP = "Public sharing admin"
OTTO_BETA_TESTER_GROUP = "Beta tester"

# Load the version from the version.yaml file
version_file_path = os.path.join(BASE_DIR, "version.yaml")
if os.path.exists(version_file_path):
    with open(version_file_path, "r") as file:
        data = yaml.safe_load(file)
        OTTO_VERSION_HASH = data.get("github_hash", "")
        OTTO_BUILD_DATE = data.get("build_date", "")

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, ".env"))
# Check for a variable we only set in the .env file to see if it exists
if os.environ.get("DJANGODB_NAME") is None:
    try:
        # These are enough to run the CI tests
        load_dotenv(os.path.join(BASE_DIR, ".env.example"))
        print("Using .env.example")
    except Exception:
        raise Exception("No .env or .env.example file found. Shutting down.")

ENVIRONMENT = os.environ.get("ENV", "LOCAL").upper()
IS_RUNNING_IN_CELERY = sys.argv and "celery" in sys.argv[0]
IS_RUNNING_IN_GITHUB = "GITHUB_ACTIONS" in os.environ
IS_RUNNING_IN_DEVOPS = "DEVOPS_PIPELINES" in os.environ
IS_RUNNING_TESTS = "test" in sys.argv or any("pytest" in arg for arg in sys.argv)
# Needs to be here for some rules checks. Just keep False for now.
IS_PROD = False

SITE_URL = urlparse(os.environ.get("SITE_URL"))

AI_SERVICES_NAME = os.environ.get("AI_SERVICES_NAME")
AZURE_AI_SERVICES_KEY = os.environ.get("AZURE_AI_SERVICES_KEY")
AZURE_DOCUMENT_INTELLIGENCE_KEY = os.environ.get("AZURE_DOCUMENT_INTELLIGENCE_KEY")
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-secret-key")
AZURE_ACCOUNT_KEY = os.environ.get(
    "AZURE_ACCOUNT_KEY"
)  # Azure as default storage requires this name to be AZURE_ACCOUNT_KEY

# AC-2, AC-19: Entra Integration
ENTRA_CLIENT_ID = os.environ.get("ENTRA_CLIENT_ID")
ENTRA_CLIENT_SECRET = os.environ.get("ENTRA_CLIENT_SECRET")
ENTRA_AUTHORITY = os.environ.get("ENTRA_AUTHORITY")
ENTRA_REDIRECT_URI = SITE_URL.geturl() + os.environ.get("ENTRA_REDIRECT_URI")
AZURE_AUTH = {
    "CLIENT_ID": ENTRA_CLIENT_ID,
    "CLIENT_SECRET": ENTRA_CLIENT_SECRET,
    "REDIRECT_URI": ENTRA_REDIRECT_URI,
    "SCOPES": ["User.Read"],
    "AUTHORITY": ENTRA_AUTHORITY,
    "USERNAME_ATTRIBUTE": "userPrincipalName",  # The AAD attribute or ID token claim you want to use as the value for the user model `USERNAME_FIELD`
    "PUBLIC_PATHS": [
        os.environ.get("ENTRA_REDIRECT_URI"),
        "/welcome",
        "/welcome/",
        "/healthz",
        "/healthz/",
        "/load_test",
        "/load_test/",
        "/metrics",
        "/metrics/",
    ],
    "USER_MAPPING_FN": "otto.utils.auth.map_entra_to_django_user",  # Optional, path to the function used to map the AAD to Django attributes
}
LOGIN_URL = "/azure_auth/login"
LOGIN_REDIRECT_URL = "/"  # Or any other endpoint

DEFAULT_CHAT_MODEL = DEFAULT_CHAT_MODEL_ID
DEFAULT_QA_MODEL = DEFAULT_QA_MODEL_ID
DEFAULT_SUMMARIZE_MODEL = DEFAULT_SUMMARIZE_MODEL_ID
DEFAULT_TRANSLATE_MODEL = DEFAULT_TRANSLATE_MODEL_ID
DEFAULT_LAWS_MODEL = DEFAULT_LAWS_MODEL_ID

DEFAULT_LAWS_LLM_PRIORITY = priorities.LOWEST
DEFAULT_DOCUMENT_LLM_PRIORITY = priorities.LOW
DEFAULT_LLM_PRIORITY = priorities.MEDIUM

DEFAULT_MONTHLY_MAX = 32  # allowance $CAD/user/month unless otherwise specified
LIBRARY_RETENTION_DAYS = 90
LIBRARY_WARN_BEFORE_DELETION_DAYS = 15
CHAT_RETENTION_DAYS = 90

PER_DOC_BATCH_SIZE = 5  # Number of documents to process in parallel for chat responses
EMBEDDING_BATCH_SIZE = 64  # Number of chunks to send to embedding model (then database insert in a transaction)
EMBED_TIME_SLICE_SECONDS = 90  # Re-schedules remainder of task after this many seconds

# HNSW Index Configuration
HNSW_THRESHOLD = 50000  # Number of chunks before HNSW index is recommended
HNSW_REBUILD_THRESHOLD = 100000  # Don't rebuild index until 2x original size


# Azure AI Services
def _normalize_endpoint(endpoint: str | None) -> str | None:
    if not endpoint:
        return None
    return endpoint if endpoint.endswith("/") else f"{endpoint}/"


_raw_azure_ai_services_endpoint = os.environ.get(
    "AZURE_AI_SERVICES_ENDPOINT"
) or os.environ.get("AZURE_OPENAI_ENDPOINT")
AZURE_AI_SERVICES_ENDPOINT = _normalize_endpoint(_raw_azure_ai_services_endpoint)
AZURE_AI_SERVICES_VERSION = os.environ.get(
    "AZURE_AI_SERVICES_VERSION"
) or os.environ.get("AZURE_OPENAI_VERSION")
AZURE_AI_SERVICES_REGION = os.environ.get("AZURE_AI_SERVICES_REGION")
EXTERNAL_TOOL_AZURE_LANGUAGE_REVIEW_ENABLED = (
    os.environ.get("EXTERNAL_TOOL_AZURE_LANGUAGE_REVIEW_ENABLED", "True") == "True"
)
EXTERNAL_TOOL_AZURE_LANGUAGE_REVIEW_ENDPOINT = (
    _normalize_endpoint(os.environ.get("EXTERNAL_TOOL_AZURE_LANGUAGE_REVIEW_ENDPOINT"))
    or AZURE_AI_SERVICES_ENDPOINT
)
EXTERNAL_TOOL_AZURE_LANGUAGE_REVIEW_API_VERSION = os.environ.get(
    "EXTERNAL_TOOL_AZURE_LANGUAGE_REVIEW_API_VERSION", "2022-05-01"
)
AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT = _normalize_endpoint(
    os.environ.get("AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT")
)
CUSTOM_TRANSLATOR_ID = os.environ.get("CUSTOM_TRANSLATOR_ID")

# Azure Speech-to-Text (batch transcription)
AZURE_SPEECH_TO_TEXT_ENDPOINT = _normalize_endpoint(
    os.environ.get("AZURE_SPEECH_TO_TEXT_ENDPOINT")
)

# Azure as default storage requires this name to be AZURE_ACCOUNT_NAME
AZURE_ACCOUNT_NAME = os.environ.get("AZURE_STORAGE_ACCOUNT_NAME", "")

# Azure as default storage requires this name to be AZURE_STORAGE_CONTAINER
AZURE_CONTAINER = os.environ.get("AZURE_STORAGE_CONTAINER", "")

AZURE_TRANSLATION_DOCUMENT_SIZE_LIMIT = 40 * 1000 * 1000  # 40 MB

DEBUG = os.environ.get("DEBUG", "False") == "True"
print("Running in debug mode:", DEBUG)
DEBUG_PROPAGATE_EXCEPTIONS = True

CHAT_DEBUG_STREAM_TESTS_ENABLED = (
    DEBUG or os.environ.get("ENABLE_CHAT_DEBUG_STREAM_TESTS", "False") == "True"
) and ENVIRONMENT != "PROD"

BROWSER_TEST_AUTH_PUBLIC_PATHS = ["/dev/browser-login", "/dev/browser-login/"]
BROWSER_TEST_AUTH_ENABLED = (
    os.environ.get("ENABLE_BROWSER_TEST_AUTH", "False") == "True"
    and ENVIRONMENT == "LOCAL"
    and DEBUG
    and (SITE_URL.hostname or "").lower() in {"localhost", "127.0.0.1"}
)
BROWSER_TEST_AUTH_UPN = (
    os.environ.get("BROWSER_TEST_AUTH_UPN", "browser.test.admin@example.com")
    .strip()
    .lower()
)
BROWSER_TEST_AUTH_EMAIL = (
    os.environ.get("BROWSER_TEST_AUTH_EMAIL", BROWSER_TEST_AUTH_UPN).strip().lower()
)
BROWSER_TEST_AUTH_FIRST_NAME = os.environ.get(
    "BROWSER_TEST_AUTH_FIRST_NAME", "Browser"
).strip()
BROWSER_TEST_AUTH_LAST_NAME = os.environ.get(
    "BROWSER_TEST_AUTH_LAST_NAME", "Test Admin"
).strip()
BROWSER_TEST_AUTH_OID = os.environ.get(
    "BROWSER_TEST_AUTH_OID", "browser-test-admin-local"
).strip()

if BROWSER_TEST_AUTH_ENABLED:
    AZURE_AUTH["PUBLIC_PATHS"].extend(BROWSER_TEST_AUTH_PUBLIC_PATHS)

# Allow for Prometheus scraping
if os.environ.get("AKS_POD_CIDR"):
    ALLOWED_CIDR_NETS = [os.environ.get("AKS_POD_CIDR")]

ALLOWED_HOSTS = [
    SITE_URL.hostname,
    "localhost",
    "127.0.0.1",
    "django-service",
    "django-service.otto.svc.cluster.local",  # Needed for Prometheus scraping in K8s
]

# AC-2: Entra Integration Helper App Configuration
AUTHENTICATION_BACKENDS = [
    "azure_auth.backends.AzureBackend",
    "rules.permissions.ObjectPermissionBackend",
]

if BROWSER_TEST_AUTH_ENABLED:
    AUTHENTICATION_BACKENDS = [
        "django.contrib.auth.backends.ModelBackend",
        *AUTHENTICATION_BACKENDS,
    ]

if IS_RUNNING_TESTS:
    AUTHENTICATION_BACKENDS = [
        "django.contrib.auth.backends.ModelBackend",
        "rules.permissions.ObjectPermissionBackend",
    ]

# Application definition
INSTALLED_APPS = [
    # Third-party apps
    "daphne",
    "django_structlog",
    "modeltranslation",
    "django_prometheus",
    "drf_spectacular",
    "rest_framework",
    # "django.contrib.admin", # Do not enable admin in production
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "django.contrib.humanize",
    "corsheaders",
    "autocomplete",
    "rules.apps.AutodiscoverRulesConfig",
    "azure_auth",  # AC-2: Entra Integration Helper App
    # Otto apps
    "otto",
    "librarian",
    "chat",
    "chat_next",
    "laws",
    # Third-party apps
    "channels",
    "django_cleanup.apps.CleanupConfig",
    "text_extractor",
    "django_celery_beat",
    "django_file_form",
    "translate",
]

MIDDLEWARE = [
    "allow_cidr.middleware.AllowCIDRMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    # SC-10, SC-23: Django default session management
    "django.contrib.sessions.middleware.SessionMiddleware",
    # AC-2, AC-3, IA-2, IA-6, IA-8: Authentication, AC-14: Limited Access
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "otto.utils.api_auth.ApiTokenAuthenticationMiddleware",
    "otto.utils.middleware.ExtendSessionMiddleware",
    # AC-3 & AC-14: Limited Access to handle login flows: redirect to login page, use Azure login, accept terms to use
    # AC-3(7), IA-8: Custom middleware for enforcing role-based access control
    "otto.utils.auth.RedirectToLoginMiddleware",
    # AC-2, AC-14, IA-2, IA-6, IA-8, SC-23: Azure AD Integration to protect entire site by default
    "otto.utils.auth.ApiAwareAzureMiddleware",
    "otto.utils.auth.AcceptTermsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "otto.utils.middleware.TimezoneMiddleware",
    "data_fetcher.middleware.GlobalRequestMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
    # AU-6: Supports structured logging, facilitating the review and analysis of audit records for inappropriate or unusual activity
    "django_structlog.middlewares.RequestMiddleware",
    "otto.utils.middleware.RequestPressureMiddleware",
    "otto.utils.middleware.HtmxMessageMiddleware",
    "otto.utils.middleware.PreventConcurrentLoginsMiddleware",
]

if IS_RUNNING_TESTS:
    MIDDLEWARE.remove("otto.utils.auth.ApiAwareAzureMiddleware")

CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = [
    "http://localhost:9000",
    "https://justipedia.gc.ca",
]


DEBUG_TOOLBAR = (
    os.environ.get("DEBUG_TOOLBAR", "False") == "True" and not IS_RUNNING_IN_CELERY
)

# If DEBUG_TOOLBAR is enabled, configure debug toolbar settings
if DEBUG_TOOLBAR:
    INSTALLED_APPS.append("debug_toolbar")
    MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")

    # Set INTERNAL_IPS based on DEBUG_TOOLBAR_IP_LIST or default to "127.0.0.1"
    INTERNAL_IPS = os.environ.get("DEBUG_TOOLBAR_IP_LIST", "127.0.0.1").split(",")

    # If DEBUG_TOOLBAR_IP_LIST is set to 127.0.0.1 and DEBUG_TOOLBAR is True,
    # the debug toolbar will only be visible for requests originating from the server machine (localhost),
    # restricting access to external devices and ensuring it's only available in local development environments.
    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_COLLAPSED": True,
        "UPDATE_ON_FETCH": True,
        "RENDER_PANELS": False,
        "DISABLE_PANELS": {
            "debug_toolbar.panels.templates.TemplatesPanel",
        },
    }


ROOT_URLCONF = "otto.urls"

TEMPLATES = [
    {
        "NAME": "django",
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "otto", "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "otto.context_processors.otto_version",
            ],
        },
    },
]

# REDIS
REDIS_HOST = os.environ.get("REDIS_HOST", "redis")
REDIS_PORT = int(os.environ.get("REDIS_PORT", "6379"))
REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"  # Celery broker & results
REDIS_CACHE_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/1"  # Django cache (django-file-form TUS metadata)
REDIS_CHANNELS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/2"  # Channels

# ASYNC - CHANNELS
WSGI_APPLICATION = "otto.wsgi.application"
ASGI_APPLICATION = "otto.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_CHANNELS_URL],
            "expiry": 60,  # Messages expire after 60s (explicit default)
            "group_expiry": 86400,  # Group memberships expire after 24h
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "TEST": {"NAME": "otto_test"},
    },
    "vector_db": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "TEST": {"NAME": "vector_test"},
    },
}

DJANGODB_PGBOUNCER = os.environ.get("DJANGODB_PGBOUNCER", "False") == "True"
VECTORDB_PGBOUNCER = os.environ.get("VECTORDB_PGBOUNCER", "False") == "True"
pgbouncer_options = {
    "DISABLE_SERVER_SIDE_CURSORS": True,
    "CONN_MAX_AGE": 0,
}

VECTORDB_MAINTENANCE_WORK_MEM_HEAVY = os.environ.get(
    "VECTORDB_MAINTENANCE_WORK_MEM_HEAVY", "512MB"
)  # used for vector db maintenance tasks

# If the database is set in the environment variables, use that instead
if os.environ.get("DJANGODB_ENGINE") is not None:
    DATABASES["default"] = {
        "ENGINE": "postgres_wrapper",
        "NAME": os.environ.get("DJANGODB_NAME"),
        "USER": os.environ.get("DJANGODB_USER"),
        "PASSWORD": os.environ.get("DJANGODB_PASSWORD", ""),
        "HOST": os.environ.get("DJANGODB_HOST"),
        "PORT": os.environ.get("DJANGODB_PORT", "5432"),
        "TEST": {
            "NAME": "test_" + os.environ.get("DJANGODB_NAME", "otto"),
        },
    }
    if DJANGODB_PGBOUNCER:
        DATABASES["default"].update(pgbouncer_options)


if os.environ.get("VECTORDB_ENGINE") is not None:
    DATABASES["vector_db"] = {
        "ENGINE": "postgres_wrapper",
        "NAME": os.environ.get("VECTORDB_NAME"),
        "USER": os.environ.get("VECTORDB_USER"),
        "PASSWORD": os.environ.get("VECTORDB_PASSWORD", ""),
        "HOST": os.environ.get("VECTORDB_HOST"),
        "PORT": os.environ.get("VECTORDB_PORT", "5432"),
        "TEST": {
            "NAME": "test_" + os.environ.get("VECTORDB_NAME", "llama_index"),
        },
    }
    if VECTORDB_PGBOUNCER:
        DATABASES["vector_db"].update(pgbouncer_options)


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


TIME_ZONE = "UTC"


REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "otto.api.authentication.OttoMachineTokenAuthentication",
        "otto.api.authentication.OttoSessionAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "URL_FORMAT_OVERRIDE": None,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Otto API",
    "DESCRIPTION": "Versioned Otto API foundation for reporting and future integrations.",
    "VERSION": "v1",
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVE_PERMISSIONS": ["otto.api.permissions.OttoApiDocsPermission"],
    "SERVE_AUTHENTICATION": [
        "otto.api.authentication.OttoSessionAuthentication",
    ],
}


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-ca"

TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True
LANGUAGES = [
    ("en", "English"),
    ("fr", "French"),
]
LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]

MODELTRANSLATION_FALLBACK_LANGUAGES = ("en", "fr")

USE_TZ = True

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

X_FRAME_OPTIONS = "SAMEORIGIN"  # Required for iframe on same origin

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# SC-10: Session Timeout
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_COOKIE_AGE = 60 * 60 * 1  # 1 hour
# Extended through middleware on all requests but /user_cost (which polls)
SESSION_SAVE_EVERY_REQUEST = False

# Security

if SITE_URL.scheme == "https" and SITE_URL.port is None:
    CSRF_TRUSTED_ORIGINS = [urlunparse(SITE_URL)]
    SECURE_SSL_REDIRECT = True
    SECURE_REDIRECT_EXEMPT = [r"^healthz/$", r"^metrics/?$", r"^load_test/?$"]
    SESSION_COOKIE_SECURE = True  # SC-23: Secure session cookies
    CSRF_COOKIE_SECURE = True
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    print("Using HTTPS")
else:
    CSRF_TRUSTED_ORIGINS = [urlunparse(SITE_URL)]
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, os.environ.get("STATIC_ROOT", "staticfiles"))
STATIC_URL = "/static/"

# Use non-manifest storage in tests so we don't require collectstatic
if IS_RUNNING_TESTS:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
else:
    # forever-cacheable files and compression support
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default Storage needs to be a local directory for append to work
DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# Azure blob storage needed for Translation
# We have already set AZURE_ACCOUNT_KEY, AZURE_ACCOUNT_NAME, AZURE_CONTAINER
AZURE_STORAGE = AzureStorage(
    account_name=AZURE_ACCOUNT_NAME,
    account_key=AZURE_ACCOUNT_KEY,
    azure_container=AZURE_CONTAINER,
)

AZURE_STORAGE_TRANSLATION_INPUT_URL_SEGMENT = "temp/translation/in"
AZURE_STORAGE_TRANSLATION_OUTPUT_URL_SEGMENT = "temp/translation/out"
AZURE_STORAGE_TRANSCRIPTION_INPUT_URL_SEGMENT = "temp/transcription/in"

# Media storage
MEDIA_ROOT = os.path.join(BASE_DIR, os.environ.get("MEDIA_ROOT", "media"))
if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT)

STORAGES = {
    # Normal disk storage
    "default": {
        "BACKEND": DEFAULT_FILE_STORAGE,
        "LOCATION": MEDIA_ROOT,
    },
    # Static files storage
    "staticfiles": {
        "BACKEND": STATICFILES_STORAGE,
        "LOCATION": STATIC_ROOT,
    },
}

AUTH_USER_MODEL = "otto.User"

# User.upn is intentionally non-unique globally to support account merges.
# Active users remain unique via the conditional DB constraint.
SILENCED_SYSTEM_CHECKS = ["auth.W004"]

# CELERY
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
LIGHT_QUEUE = "light"
HEAVY_QUEUE = "heavy"
EMBED_QUEUE = "embed"
CELERY_TASK_DEFAULT_QUEUE = LIGHT_QUEUE
# Improve fairness: reduce prefetch so a single long task doesn't monopolize the worker
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
# Safer acknowledgements so tasks re-queue if a worker dies mid-slice
# Use the proper Celery config name via namespace mapping
CELERY_TASK_ACKS_LATE = True
# Report STARTED state for long-running tasks so pollers and incident logs can
# distinguish queued work from work that has actually begun executing.
CELERY_TASK_TRACK_STARTED = True
# Give workers a short soft-shutdown window so late-acked Redis tasks can be
# handed back cleanly during normal pod termination.
CELERY_WORKER_SOFT_SHUTDOWN_TIMEOUT = 30
CELERY_WORKER_ENABLE_SOFT_SHUTDOWN_ON_IDLE = True
# Periodically recycle prefork child processes to reclaim fragmented memory.
# Only relevant for prefork pool (heavyworker); ignored by gevent workers.
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100
# Replace a child process if it exceeds ~2 GB. Set high enough that heavy tasks
# (LLM context windows, large doc extraction) can complete; pods are 4–8 Gi.
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 2000000  # KB (~2 GB)

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": f"otto_{ENVIRONMENT}",
    }
}


DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
DATA_UPLOAD_MAX_NUMBER_FILES = 2000

# Logging

LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO")
CELERY_LOG_LEVEL = os.environ.get("CELERY_LOG_LEVEL", "INFO")
DJANGO_STRUCTLOG_CELERY_ENABLED = True
DJANGO_STRUCTLOG_COMMAND_LOGGING_ENABLED = True

LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "json_formatter": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.processors.JSONRenderer(),
        },
        "console": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.dev.ConsoleRenderer(),
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
            "filters": ["raise_endpoint_level"],
        },
        "json": {
            "class": "logging.StreamHandler",
            "formatter": "json_formatter",
            "filters": ["raise_endpoint_level"],
        },
        "null": {
            "class": "logging.NullHandler",
        },
    },
    "root": {
        "handlers": ["json"],
        "level": LOG_LEVEL,
        "stream": sys.stdout,
    },
    "filters": {
        "raise_endpoint_level": {
            "()": "otto.utils.logging.RaiseLevelForEndpointsFilter",
        },
    },
}

if ENVIRONMENT == "LOCAL":
    LOGGING["root"]["handlers"] = ["console"]
elif IS_RUNNING_TESTS:
    LOGGING["root"]["handlers"] = ["null"]

# AU-6 & AU-7: Allows for the adjustment of log levels based on the environment and operational needs
structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.stdlib.filter_by_level,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.CallsiteParameterAdder(
            [
                structlog.processors.CallsiteParameter.PATHNAME,
                structlog.processors.CallsiteParameter.FUNC_NAME,
                structlog.processors.CallsiteParameter.LINENO,
            ]
        ),
        logging_utils.merge_pathname_lineno_function_to_location,
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)


def _load_content_ingestion_allowed_domains(file_path: Path) -> list[str]:
    if not file_path.exists():
        raise FileNotFoundError(
            f"Content-ingestion allowlist file not found: {file_path}"
        )

    domains = [
        line.strip()
        for line in file_path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]

    if not domains:
        raise ValueError(f"Content-ingestion allowlist file is empty: {file_path}")

    return domains


CONTENT_INGESTION_ALLOWED_DOMAINS_FILE = (
    BASE_DIR / "otto" / "data" / "content_ingestion_domains.txt"
)
CONTENT_INGESTION_ALLOWED_DOMAINS = _load_content_ingestion_allowed_domains(
    CONTENT_INGESTION_ALLOWED_DOMAINS_FILE
)
ALLOWED_FETCH_URLS = CONTENT_INGESTION_ALLOWED_DOMAINS

WARN_COST = 0.5

FILE_FORM_UPLOAD_DIR = "tmp_uploads_dir"
FILE_FORM_MUST_LOGIN = True
# The default chunkSize for file uploads in Django-File-Form is 2.5MB
# Reducing to 1MB means that it should always write chunks to disk (to avoid stateful memory issues)
FILE_UPLOAD_MAX_MEMORY_SIZE = 1 * 1024 * 1024

# Ensure uploaded files are moved, not copied, to avoid memory spikes
FILE_FORM_ALWAYS_COPY_UPLOADED_FILE = False


temp_upload_dir = os.path.join(MEDIA_ROOT, FILE_FORM_UPLOAD_DIR)

os.makedirs(temp_upload_dir, exist_ok=True)
