# Generated by Django 5.1.5 on 2025-02-12 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("otto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(default="Untitled request", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("merged", models.BooleanField(default=False)),
                ("access_controls", models.ManyToManyField(to="otto.accesscontrol")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutputFile",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="ocr_output_files/"
                    ),
                ),
                (
                    "txt_file",
                    models.FileField(
                        blank=True, null=True, upload_to="ocr_output_files/"
                    ),
                ),
                ("usd_cost", models.FloatField(default=0.0)),
                ("file_name", models.TextField(default="tmp")),
                (
                    "celery_task_ids",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("access_controls", models.ManyToManyField(to="otto.accesscontrol")),
                (
                    "user_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_files",
                        to="text_extractor.userrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
