# Generated by Django 5.0.7 on 2024-07-25 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("otto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(default="Untitled request", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("access_controls", models.ManyToManyField(to="otto.accesscontrol")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutputFile",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("file_id", models.CharField(blank=True, max_length=255, null=True)),
                ("file", models.FileField(upload_to="ocr_output_files/")),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("access_controls", models.ManyToManyField(to="otto.accesscontrol")),
                (
                    "user_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_files",
                        to="text_extractor.userrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
