# Generated by Django 5.1.8 on 2025-04-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_extractor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outputfile",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
