# Generated by Django 5.1.8 on 2025-08-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_extractor", "0002_outputfile_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="outputfile",
            name="is_merged",
            field=models.BooleanField(default=False),
        ),
    ]
