# Generated by Django 5.2.7 on 2025-10-23 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0008_ottostatus_normal_chat_max_mb_and_more"),
        ("text_extractor", "0002_outputfile_error_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="InputFile",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("file", models.FileField(upload_to="text_extractor_input_files/")),
                ("original_filename", models.CharField(max_length=500)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("access_controls", models.ManyToManyField(to="otto.accesscontrol")),
                (
                    "user_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_files",
                        to="text_extractor.userrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
