# Generated by Django 5.1.1 on 2024-11-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_extractor", "0002_remove_outputfile_file_id_alter_outputfile_file_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outputfile",
            name="file",
        ),
        migrations.AddField(
            model_name="outputfile",
            name="celery_task_ids",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="outputfile",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="ocr_output_files/"
            ),
        ),
        migrations.AddField(
            model_name="outputfile",
            name="txt_file",
            field=models.FileField(
                blank=True, null=True, upload_to="ocr_output_files/"
            ),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="merged",
            field=models.BooleanField(default=False),
        ),
    ]
