# Generated by Django 5.1 on 2024-10-28 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_extractor", "0002_remove_outputfile_file_id_alter_outputfile_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="outputfile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
