# Generated by Django 5.2.9 on 2025-12-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_extractor", "0003_inputfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrequest",
            name="ai_model",
            field=models.CharField(default="document_intelligence", max_length=64),
        ),
    ]
