# Generated by Django 5.1.1 on 2024-11-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "text_extractor",
            "0003_remove_outputfile_file_outputfile_celery_task_ids_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="outputfile",
            name="usd_cost",
            field=models.FloatField(default=0.0),
        ),
    ]
