# Generated by Django 5.1 on 2024-10-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("text_extractor", "0003_outputfile_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outputfile",
            name="created_at",
        ),
    ]
