# Generated by Django 6.0.3 on 2026-03-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0022_add_chat_next_tour_completed"),
        ("text_extractor", "0004_userrequest_ai_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputfile",
            name="access_controls",
            field=models.ManyToManyField(related_name="+", to="otto.accesscontrol"),
        ),
        migrations.AlterField(
            model_name="outputfile",
            name="access_controls",
            field=models.ManyToManyField(related_name="+", to="otto.accesscontrol"),
        ),
        migrations.AlterField(
            model_name="userrequest",
            name="access_controls",
            field=models.ManyToManyField(related_name="+", to="otto.accesscontrol"),
        ),
    ]
