from template_wizard.views.docx_template import (
    docx_template_status,
    remove_docx_template,
    upload_docx_template,
)
from template_wizard.views.download_all import download_all_results
from template_wizard.views.fields import delete_field, edit_fields, field_modal
from template_wizard.views.fill_template import (
    fill_template,
    poll_status,
    restart_source_processing,
    source_raw_data,
    source_template_result,
)
from template_wizard.views.layout import edit_layout, test_layout
from template_wizard.views.llm_fields import generate_fields, modify_fields, test_fields
from template_wizard.views.llm_layout import generate_jinja, modify_layout_code
from template_wizard.views.main import (
    delete_session,
    new_session,
    open_session,
    session_history,
    template_list,
)
from template_wizard.views.sources import (
    add_file_source,
    add_text_source,
    add_url_source,
    delete_all_sources,
    delete_source,
    download_source_file,
    select_sources,
)
from template_wizard.views.template import (
    delete_template,
    edit_example_source,
    edit_metadata,
    new_template,
    update_example_type,
)

app_name = "template_wizard"

from django.urls import path

urlpatterns = [
    path("", template_list, name="index"),
    path("new_template/", new_template, name="new_template"),
    path(
        "edit_template/<int:template_id>/metadata/",
        edit_metadata,
        name="edit_template",
    ),
    path(
        "edit_template/<int:template_id>/metadata/",
        edit_metadata,
        name="edit_metadata",
    ),
    path(
        "edit_template/<int:template_id>/source/",
        edit_example_source,
        name="edit_example_source",
    ),
    path(
        "edit_template/<int:template_id>/fields/",
        edit_fields,
        name="edit_fields",
    ),
    path(
        "edit_template/<int:template_id>/layout/",
        edit_layout,
        name="edit_layout",
    ),
    path(
        "delete_template/<int:template_id>/",
        delete_template,
        name="delete_template",
    ),
    path(
        "edit_template/<int:template_id>/field_modal/",
        field_modal,
        name="field_modal",
    ),
    path(
        "edit_template/<int:template_id>/field_modal/parent/<int:parent_field_id>/",
        field_modal,
        name="field_modal",
    ),
    path(
        "edit_template/<int:template_id>/field_modal/<int:field_id>/",
        field_modal,
        name="field_modal",
    ),
    path(
        "edit_template/<int:template_id>/delete_field/<int:field_id>/",
        delete_field,
        name="delete_field",
    ),
    path(
        "edit_template/<int:template_id>/test_fields/",
        test_fields,
        name="test_fields",
    ),
    path(
        "edit_template/<int:template_id>/test_fields/<int:source_id>/",
        test_fields,
        name="test_fields",
    ),
    path(
        "edit_template/<int:template_id>/test_layout/",
        test_layout,
        name="test_layout",
    ),
    path(
        "edit_template/<int:template_id>/generate_jinja/",
        generate_jinja,
        name="generate_jinja",
    ),
    path(
        "edit_template/<int:template_id>/modify_layout_code/",
        modify_layout_code,
        name="modify_layout_code",
    ),
    path(
        "edit_template/<int:template_id>/generate_fields/<str:from_mode>/",
        generate_fields,
        name="generate_fields",
    ),
    path(
        "edit_template/<int:template_id>/modify_fields/",
        modify_fields,
        name="modify_fields",
    ),
    path(
        "new_session/<int:template_id>/",
        new_session,
        name="new_session",
    ),
    path(
        "session/<int:session_id>/select_sources/",
        select_sources,
        name="select_sources",
    ),
    path(
        "session/<int:session_id>/fill_template/",
        fill_template,
        name="fill_template",
    ),
    path(
        "session/<int:session_id>/add_url_source/",
        add_url_source,
        name="add_url_source",
    ),
    path(
        "source/<int:source_id>/download/",
        download_source_file,
        name="download_source_file",
    ),
    path(
        "source/<int:source_id>/delete/",
        delete_source,
        name="delete_source",
    ),
    path(
        "session/<int:session_id>/delete_all_sources/",
        delete_all_sources,
        name="delete_all_sources",
    ),
    path("session_history/", session_history, name="session_history"),
    path("delete_session/<int:session_id>/", delete_session, name="delete_session"),
    path("open_session/<int:session_id>/", open_session, name="open_session"),
    path(
        "session/<int:session_id>/source/<int:source_id>/raw_data/",
        source_raw_data,
        name="source_raw_data",
    ),
    path(
        "session/<int:session_id>/source/<int:source_id>/template_result/",
        source_template_result,
        name="source_template_result",
    ),
    path(
        "session/<int:session_id>/poll_status/",
        poll_status,
        name="poll_status",
    ),
    path(
        "session/<int:session_id>/source/<int:source_id>/restart_processing/",
        restart_source_processing,
        name="restart_source_processing",
    ),
    path(
        "session/<int:session_id>/download_all/",
        download_all_results,
        name="download_all_results",
    ),
    path(
        "session/<int:session_id>/add_text_source/",
        add_text_source,
        name="add_text_source",
    ),
    path(
        "session/<int:session_id>/add_file_source/",
        add_file_source,
        name="add_file_source",
    ),
    path(
        "update_example_type/<int:source_id>/",
        update_example_type,
        name="update_example_type",
    ),
    path(
        "edit_template/<int:template_id>/upload_docx_template/",
        upload_docx_template,
        name="upload_docx_template",
    ),
    path(
        "edit_template/<int:template_id>/remove_docx_template/",
        remove_docx_template,
        name="remove_docx_template",
    ),
    path(
        "edit_template/<int:template_id>/docx_template_status/",
        docx_template_status,
        name="docx_template_status",
    ),
]
