# Generated by Django 5.1.1 on 2024-12-02 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0040_alter_chatfile_filename"),
        ("laws", "0002_remove_law_lang_remove_law_law_id_and_more"),
        ("librarian", "0015_alter_document_extracted_title_and_more"),
        ("otto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100, null=True)),
                ("name_fr", models.CharField(max_length=100, null=True)),
                ("short_name", models.CharField(max_length=50, null=True, unique=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_fr", models.TextField(null=True)),
                ("unit_name", models.CharField(default="units", max_length=50)),
                (
                    "unit_name_en",
                    models.CharField(default="units", max_length=50, null=True),
                ),
                (
                    "unit_name_fr",
                    models.CharField(default="units", max_length=50, null=True),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=6, default=1, max_digits=10),
                ),
                ("unit_quantity", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="OttoStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("laws_last_refreshed", models.DateTimeField(blank=True, null=True)),
                ("exchange_rate", models.FloatField(default=1.38)),
            ],
        ),
        migrations.CreateModel(
            name="Pilot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pilot_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("service_unit", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="feature",
            name="short_name",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="url_context",
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name="user",
            name="default_preset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for",
                to="chat.preset",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="weekly_bonus",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="weekly_max",
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="feature",
            name="category",
            field=models.CharField(
                choices=[
                    ("ai_assistant", "AI Assistant"),
                    ("monitoring", "Monitoring"),
                    ("reporting", "Reporting"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="feedback_type",
            field=models.CharField(
                choices=[
                    ("feedback", "Feedback"),
                    ("bug", "Bug"),
                    ("question", "Question"),
                    ("feature_request", "Feature request"),
                    ("other", "Other"),
                ],
                default="feedback",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="otto_version",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="Cost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=1)),
                ("date_incurred", models.DateField(auto_now_add=True)),
                ("usd_cost", models.DecimalField(decimal_places=6, max_digits=12)),
                (
                    "feature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("librarian", "Librarian"),
                            ("qa", "Q&A"),
                            ("chat", "Chat"),
                            ("chat_agent", "Chat agent"),
                            ("translate", "Translate"),
                            ("summarize", "Summarize"),
                            ("template_wizard", "Template Wizard"),
                            ("laws_query", "Legislation Search"),
                            ("laws_load", "Legislation loading"),
                            ("text_extractor", "Text extractor"),
                            ("lex_experiment", "Lex experiment"),
                            ("load_test", "Load test"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="librarian.document",
                    ),
                ),
                (
                    "law",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="laws.law",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cost_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="otto.costtype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="pilot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="otto.pilot",
            ),
        ),
    ]
