# Generated by Django 5.1.6 on 2025-03-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ai_assistant_tour_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="homepage_tour_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="laws_search_tour_completed",
            field=models.BooleanField(default=False),
        ),
    ]
