# Generated by Django 5.1.6 on 2025-04-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0002_user_ai_assistant_tour_completed_and_more"),
        ("otto", "0002_visitor"),
    ]

    operations = []
