# Generated by Django 5.1 on 2024-08-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0002_costtype_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="cost",
            name="count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="costtype",
            name="short_name",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="costtype",
            name="unit_cost",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name="costtype",
            name="unit_name",
            field=models.CharField(default="units", max_length=50),
        ),
        migrations.AddField(
            model_name="costtype",
            name="unit_name_en",
            field=models.CharField(default="units", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="costtype",
            name="unit_name_fr",
            field=models.CharField(default="units", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="costtype",
            name="unit_quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="feature",
            name="short_name",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cost",
            name="amount",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
