# Generated by Django 5.1.8 on 2025-06-11 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0003_merge_20250401_2012"),
    ]

    operations = [
        migrations.AddField(
            model_name="ottostatus",
            name="terms_last_updated",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
