# Generated by Django 5.1.8 on 2025-06-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0004_ottostatus_terms_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="ottostatus",
            name="laws_status",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
