# Generated by Django 5.1.8 on 2025-07-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0004_ottostatus_terms_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="otto_version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In progress"),
                    ("resolved", "Resolved"),
                    ("deferred", "Deferred"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=16,
            ),
        ),
    ]
