# Generated by Django 5.1 on 2024-09-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0004_pilot_user_pilot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="date_incurred",
            field=models.DateField(auto_now_add=True),
        ),
    ]
