# Generated by Django 5.1 on 2024-09-13 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0008_law_sha_256_hash_en_law_sha_256_hash_fr"),
        ("otto", "0005_alter_cost_date_incurred"),
    ]

    operations = [
        migrations.AddField(
            model_name="cost",
            name="law",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="laws.law",
            ),
        ),
    ]
