# Generated by Django 5.1.8 on 2025-07-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0005_alter_feedback_otto_version_alter_feedback_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="otto_version",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In progress"),
                    ("deferred", "Deferred"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=16,
            ),
        ),
    ]
