# Generated by Django 5.1.8 on 2025-07-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0005_ottostatus_laws_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ottostatus",
            name="laws_status",
        ),
    ]
