# Generated by Django 5.1 on 2024-09-12 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_remove_preset_default_for"),
        ("otto", "0005_alter_cost_date_incurred"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_preset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for",
                to="chat.preset",
            ),
        ),
    ]
