# Generated by Django 5.1.8 on 2025-07-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0006_alter_feedback_otto_version_alter_feedback_status"),
        ("otto", "0006_remove_ottostatus_laws_status"),
    ]

    operations = []
