# Generated by Django 5.1 on 2024-09-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0006_cost_law"),
        ("otto", "0006_user_default_preset"),
    ]

    operations = []
