# Generated by Django 5.1.8 on 2025-08-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_remove_chat_security_label"),
        ("librarian", "0004_remove_datasource_security_label"),
        ("otto", "0007_merge_20250711_1338"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SecurityLabel",
        ),
    ]
