# Generated by Django 5.1 on 2024-09-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0007_alter_cost_feature"),
        ("otto", "0007_merge_0006_cost_law_0006_user_default_preset"),
    ]

    operations = []
