# Generated by Django 5.1 on 2024-10-11 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0022_remove_chat_data_source_remove_chat_options_and_more"),
        ("laws", "0002_remove_law_lang_remove_law_law_id_and_more"),
        ("librarian", "0009_datasource_chat"),
        ("otto", "0007_alter_cost_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="cost_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="otto.costtype",
            ),
        ),
        migrations.AlterField(
            model_name="cost",
            name="document",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="librarian.document",
            ),
        ),
        migrations.AlterField(
            model_name="cost",
            name="law",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="laws.law"
            ),
        ),
        migrations.AlterField(
            model_name="cost",
            name="message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat.message",
            ),
        ),
        migrations.AlterField(
            model_name="cost",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
