# Generated by Django 5.1.8 on 2025-09-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0007_merge_20250711_1338"),
    ]

    operations = [
        migrations.AddField(
            model_name="ottostatus",
            name="normal_chat_max_mb",
            field=models.IntegerField(
                blank=True,
                default=25,
                help_text="Max chat upload size (MB) for normal users",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ottostatus",
            name="normal_librarian_max_mb",
            field=models.IntegerField(
                blank=True,
                default=50,
                help_text="Max librarian upload size (MB) for normal users",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ottostatus",
            name="steward_chat_max_mb",
            field=models.IntegerField(
                blank=True,
                default=50,
                help_text="Max chat upload size (MB) for Data stewards",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ottostatus",
            name="steward_librarian_max_mb",
            field=models.IntegerField(
                blank=True,
                default=500,
                help_text="Max librarian upload size (MB) for Data stewards",
                null=True,
            ),
        ),
    ]
