# Generated by Django 5.1 on 2024-10-01 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_remove_chatoptions_preset_name_and_more"),
        ("otto", "0007_alter_cost_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_preset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for",
                to="chat.preset",
            ),
        ),
    ]
