# Generated by Django 5.2.8 on 2025-11-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0030_chat_chat_chat_user_id_4f3805_idx_and_more"),
        ("otto", "0008_ottostatus_normal_chat_max_mb_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["status", "-created_at"], name="otto_feedba_status_2f94bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["feedback_type", "-created_at"],
                name="otto_feedba_feedbac_98713c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["app", "-created_at"], name="otto_feedba_app_cda6d5_idx"
            ),
        ),
    ]
