# Generated by Django 5.1 on 2024-10-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0008_alter_cost_cost_type_alter_cost_document_and_more"),
        ("otto", "0008_user_default_preset"),
    ]

    operations = []
