# Generated by Django 5.2.8 on 2025-11-19 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0009_feedback_otto_feedba_status_2f94bd_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="pilot",
        ),
        migrations.AlterField(
            model_name="cost",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CostGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost_group_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100, null=True)),
                ("name_fr", models.CharField(max_length=100, null=True)),
                (
                    "lex_file_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "monthly_max",
                    models.IntegerField(
                        default=300,
                        help_text="Monthly budget limit in CAD for this cost group",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who can select this cost group for cost tracking",
                        related_name="available_cost_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cost",
            name="cost_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="otto.costgroup",
            ),
        ),
        migrations.DeleteModel(
            name="Pilot",
        ),
    ]
