# Generated by Django 5.1 on 2024-10-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0009_alter_cost_cost_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="daily_max",
            field=models.IntegerField(default=25),
        ),
    ]
