# Generated by Django 5.1 on 2024-10-11 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0009_merge_20241011_1541"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="cost_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="otto.costtype",
            ),
        ),
    ]
