# Generated by Django 5.1 on 2024-10-15 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0009_alter_cost_cost_type"),
        ("otto", "0010_alter_cost_cost_type"),
    ]

    operations = []
