# Generated by Django 5.2.9 on 2025-12-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0010_remove_user_pilot_alter_cost_user_costgroup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="request_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
