# Generated by Django 5.2.9 on 2026-01-08 15:52

from django.db import migrations


def remove_app_user_groups(apps, schema_editor):
    """Remove app-specific user groups that are no longer needed."""
    Group = apps.get_model("auth", "Group")
    
    # Delete app-specific groups
    app_groups = [
        "AI Assistant user",
        "Legislation Search user",
        "Text Extractor user",
    ]
    
    Group.objects.filter(name__in=app_groups).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("otto", "0011_alter_cost_request_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="app",
        ),
        migrations.DeleteModel(
            name="App",
        ),
        migrations.DeleteModel(
            name="Feature",
        ),
        migrations.RunPython(
            remove_app_user_groups,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
