# Generated by Django 5.2.9 on 2025-12-29 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0036_alter_chatoptions_qa_mode"),
        ("otto", "0011_alter_cost_request_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="loaded_preset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks",
                to="chat.preset",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="preset_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
