# Generated by Django 5.1 on 2024-10-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0011_merge_20241015_2016"),
        ("otto", "0012_remove_user_weekly_max_override_user_weekly_bonus"),
    ]

    operations = []
