# Generated by Django 5.1 on 2024-11-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0012_remove_user_weekly_max_override_user_weekly_bonus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="otto_version",
            field=models.CharField(max_length=50),
        ),
    ]
