# Generated by Django 5.2.9 on 2026-01-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0012_feedback_loaded_preset_feedback_preset_snapshot"),
        ("otto", "0012_remove_feature_app_delete_app_delete_feature"),
    ]

    operations = []
