# Generated by Django 5.2.9 on 2026-01-12 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0001_initial"),
        ("otto", "0013_merge_20260112_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_next_default_preset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_next",
                to="chat_next.preset",
            ),
        ),
    ]
