# Generated by Django 5.1 on 2024-11-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0013_alter_feedback_otto_version"),
        ("otto", "0013_merge_20241018_2115"),
    ]

    operations = []
