# Generated by Django 5.2.11 on 2026-02-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0039_remove_qa_prune"),
        ("laws", "0017_alter_law_eng_law_id"),
        ("librarian", "0016_datasource_librarian_d_order_97bb87_idx_and_more"),
        ("otto", "0013_merge_20260112_1522"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cost",
            index=models.Index(
                fields=["user", "date_incurred"], name="otto_cost_user_id_02f4db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cost",
            index=models.Index(
                fields=["user", "cost_group", "date_incurred"],
                name="otto_cost_user_id_879454_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cost",
            index=models.Index(
                fields=["cost_group", "date_incurred"],
                name="otto_cost_cost_gr_46a3f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cost",
            index=models.Index(
                fields=["feature", "date_incurred"], name="otto_cost_feature_51f6c9_idx"
            ),
        ),
    ]
