# Generated by Django 5.1 on 2024-11-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0014_merge_20241104_1813"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="addressed",
            field=models.BooleanField(default=False),
        ),
    ]
