# Generated by Django 5.2.9 on 2026-01-14 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0002_add_response_output_field"),
        ("otto", "0014_user_chat_next_default_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="cost",
            name="message_next",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat_next.message",
            ),
        ),
    ]
