# Generated by Django 5.2.11 on 2026-02-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0015_add_otto_user_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="notification",
            name="text_en",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="text_fr",
            field=models.TextField(null=True),
        ),
    ]
