# Generated by Django 5.1.1 on 2024-11-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0015_ottostatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="ottostatus",
            name="exchange_rate",
            field=models.FloatField(default=1.38),
        ),
    ]
