# Generated by Django 5.1 on 2024-11-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0015_alter_feedback_feedback_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=16,
            ),
        ),
    ]
