# Generated by Django 5.2.11 on 2026-02-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0015_add_message_next_to_cost"),
        ("otto", "0015_add_otto_user_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_ai_assistant",
            field=models.CharField(
                choices=[("chat", "chat"), ("chat_next", "chat_next")],
                default="chat",
                max_length=20,
            ),
        ),
    ]
