# Generated by Django 5.1.1 on 2024-11-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0016_ottostatus_exchange_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="feature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("librarian", "Librarian"),
                    ("qa", "Q&A"),
                    ("chat", "Chat"),
                    ("chat_agent", "Chat agent"),
                    ("translate", "Translate"),
                    ("summarize", "Summarize"),
                    ("template_wizard", "Template Wizard"),
                    ("laws_query", "Legislation Search"),
                    ("laws_load", "Legislation loading"),
                    ("text_extractor", "Text Extractor"),
                    ("load_test", "Load test"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="category",
            field=models.CharField(
                choices=[
                    ("ai_assistant", "AI Assistant"),
                    ("monitoring", "Monitoring"),
                    ("reporting", "Reporting"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
