# Generated by Django 5.2.11 on 2026-03-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0016_alter_notification_text_alter_notification_text_en_and_more"),
        ("otto", "0016_user_default_ai_assistant"),
    ]

    operations = []
