# Generated by Django 5.1 on 2024-11-21 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0016_feedback_priority_feedback_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
