# Generated by Django 5.1.1 on 2024-11-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0017_alter_cost_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="feature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("librarian", "Librarian"),
                    ("qa", "Q&A"),
                    ("chat", "Chat"),
                    ("chat_agent", "Chat agent"),
                    ("translate", "Translate"),
                    ("summarize", "Summarize"),
                    ("template_wizard", "Template wizard"),
                    ("laws_query", "Legislation search"),
                    ("laws_load", "Legislation loading"),
                    ("text_extractor", "Text extractor"),
                    ("lex_experiment", "Lex experiment"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
