# Generated by Django 5.2.11 on 2026-03-04 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0008_alter_chatoptions_chat_reasoning_effort"),
        ("otto", "0017_merge_20260304_1825"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="chat_message_next",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback_set",
                to="chat_next.message",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="loaded_preset_next",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks",
                to="chat_next.preset",
            ),
        ),
        migrations.AlterField(
            model_name="cost",
            name="feature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("librarian", "Librarian"),
                    ("qa", "Q&A"),
                    ("chat", "Chat"),
                    ("chat_agent", "Chat agent"),
                    ("chat_next", "AI Assistant (beta)"),
                    ("translate", "Translate"),
                    ("summarize", "Summarize"),
                    ("template_wizard", "Template Wizard"),
                    ("laws_query", "Legislation Search"),
                    ("laws_load", "Legislation loading"),
                    ("text_extractor", "Text Extractor"),
                    ("load_test", "Load test"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
