# Generated by Django 5.2.11 on 2026-03-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0018_feedback_chat_message_next_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="feature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("librarian", "Librarian"),
                    ("qa", "Q&A"),
                    ("chat", "Chat"),
                    ("chat_next", "AI Assistant (beta)"),
                    ("translate", "Translate"),
                    ("summarize", "Summarize"),
                    ("template_wizard", "Template Wizard"),
                    ("laws_query", "Legislation Search"),
                    ("laws_load", "Legislation loading"),
                    ("text_extractor", "Text Extractor"),
                    ("load_test", "Load test"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
