# Generated by Django 5.1 on 2024-11-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0018_feedback_url_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="feedback_type",
            field=models.CharField(
                choices=[
                    ("feedback", "Feedback"),
                    ("bug", "Bug"),
                    ("question", "Question"),
                    ("feature_request", "Feature request"),
                    ("other", "Other"),
                ],
                default="feedback",
                max_length=50,
            ),
        ),
    ]
