# Generated by Django 5.1 on 2024-11-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0016_ottostatus_exchange_rate"),
        ("otto", "0019_alter_feedback_feedback_type"),
    ]

    operations = []
