# Generated by Django 6.0.3 on 2026-03-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0020_alter_cost_feature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="loaded_preset_next",
        ),
        migrations.RemoveField(
            model_name="user",
            name="chat_next_default_preset",
        ),
    ]
