# Generated by Django 5.1 on 2024-11-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0017_alter_cost_feature_alter_feature_category"),
        ("otto", "0020_merge_20241122_2011"),
    ]

    operations = []
