# Generated by Django 6.0.3 on 2026-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0021_remove_feedback_loaded_preset_next_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_next_tour_completed",
            field=models.BooleanField(default=False),
        ),
    ]
