# Generated by Django 5.1 on 2024-11-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0019_merge_20241127_2121"),
        ("otto", "0021_merge_20241127_1803"),
    ]

    operations = []
