# Generated by Django 5.1.1 on 2024-12-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0022_rename_weekly_bonus_user_monthly_bonus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
