# Generated by Django 5.1.1 on 2024-12-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0022_merge_20241129_1525"),
        ("otto", "0022_rename_weekly_bonus_user_monthly_bonus_and_more"),
    ]

    operations = []
