# Generated by Django 6.0.3 on 2026-03-31 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0021_user_upn_ci_unique_active"),
        ("otto", "0022_add_chat_next_tour_completed"),
    ]

    operations = []
