# Generated by Django 5.1.4 on 2025-01-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0023_blockedurl"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UsageTerm",
        ),
    ]
