# Generated by Django 5.1.1 on 2024-12-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0023_blockedurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="feature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("librarian", "Librarian"),
                    ("qa", "Q&A"),
                    ("chat", "Chat"),
                    ("chat_agent", "Chat agent"),
                    ("translate", "Translate"),
                    ("summarize", "Summarize"),
                    ("template_wizard", "Template Wizard"),
                    ("laws_query", "Legislation Search"),
                    ("laws_load", "Legislation loading"),
                    ("text_extractor", "Text Extractor"),
                    ("load_test", "Load test"),
                    ("concierge_service", "Concierge Service"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
