# Generated by Django 5.1.1 on 2024-12-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0023_blockedurl"),
        ("otto", "0024_alter_cost_feature"),
    ]

    operations = []
