# Generated by Django 6.0.3 on 2026-03-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0023_merge_20260331_1823"),
        ("otto", "0024_team_name_ci_unique"),
    ]

    operations = []
