# Generated by Django 5.1.4 on 2025-02-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0025_reset_accepted_terms_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="heading_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="heading_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="text_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="text_fr",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
