# Generated by Django 5.1.1 on 2025-01-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0025_intake"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intake",
            name="further_details",
            field=models.TextField(blank=True),
        ),
    ]
