# Generated by Django 5.1.1 on 2025-01-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0026_alter_intake_further_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intake",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("asap", "As soon as possible (ASAP)"),
                    ("eod", "End of day (EOD)"),
                    ("tomorrow", "Tomorrow"),
                    ("not_urgent", "Not urgent"),
                ],
                default="asap",
                max_length=50,
            ),
        ),
    ]
