# Generated by Django 6.0.4 on 2026-04-24 15:19

import otto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0026_ottostatus_librarian_auto_embed_max_chunks"),
    ]

    operations = [
        migrations.AddField(
            model_name="ottostatus",
            name="external_tool_review_flag_credentials_or_secrets",
            field=models.BooleanField(
                default=True,
                help_text="Treat credential-like text such as API keys, tokens, passwords, and connection strings as approval-warning signals.",
            ),
        ),
        migrations.AddField(
            model_name="ottostatus",
            name="external_tool_review_flag_large_payloads",
            field=models.BooleanField(
                default=True,
                help_text="Treat unusually large outbound text payloads as approval-warning signals.",
            ),
        ),
        migrations.AddField(
            model_name="ottostatus",
            name="external_tool_review_flag_local_pii",
            field=models.BooleanField(
                default=True,
                help_text="Treat local regex matches like email addresses, phone numbers, and social insurance numbers as approval-warning signals.",
            ),
        ),
        migrations.AddField(
            model_name="ottostatus",
            name="external_tool_review_flag_privileged_or_classified",
            field=models.BooleanField(
                default=False,
                help_text="Treat phrase-only matches like ‘classified’, ‘cabinet confidence’, or ‘solicitor-client’ as approval-warning signals.",
            ),
        ),
        migrations.AddField(
            model_name="ottostatus",
            name="external_tool_review_flagged_azure_pii_categories",
            field=models.JSONField(
                blank=True,
                default=otto.models.default_external_tool_review_flagged_azure_pii_categories,
                help_text="Azure Language PII categories that should count as approval-warning signals for external-tool requests.",
            ),
        ),
    ]
