# Generated by Django 5.1.4 on 2025-02-06 15:28

from django.db import migrations
from otto.management.commands.reset_app_data import Command as ResetAppDataCommand


def reset_apps(apps, schema_editor):
    ResetAppDataCommand().reset_apps()


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0026_notification_heading_en_notification_heading_fr_and_more"),
    ]

    operations = [
        migrations.RunPython(reset_apps),
    ]
