# Generated by Django 5.1.5 on 2025-02-11 21:37
"""
Set all otto.models.User object monthly_max to settings.DEFAULT_MONTHLY_MAX
"""

from django.db import migrations
from django.conf import settings


def set_default_monthly_max(apps, schema_editor):
    User = apps.get_model("otto", "User")
    User.objects.update(monthly_max=settings.DEFAULT_MONTHLY_MAX)


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0027_auto_20250206_1528"),
    ]

    operations = [
        migrations.RunPython(set_default_monthly_max),
    ]
