# Generated by Django 5.1.1 on 2025-01-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0027_alter_intake_urgency"),
    ]

    operations = [
        migrations.AddField(
            model_name="intake",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted to Concierge Team"),
                    ("in_progress", "In progress"),
                    ("awaiting_response", "Awaiting response"),
                    ("complete", "Complete"),
                ],
                default="submitted",
                max_length=50,
            ),
        ),
    ]
