# Generated by Django 5.1.1 on 2025-01-02 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0028_intake_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intake",
            name="id",
        ),
        migrations.AddField(
            model_name="intake",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
