# Generated by Django 6.0.4 on 2026-05-20 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0028_enable_organization_default_external_tool_review_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "secret_hash",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("secret_last_rotated_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_used_ip",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_api_clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ApiClientAllowedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cidr", models.CharField(max_length=64)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_ip_ranges",
                        to="otto.apiclient",
                    ),
                ),
            ],
            options={
                "ordering": ["cidr"],
            },
        ),
        migrations.CreateModel(
            name="ApiClientAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("secret_rotated", "Secret rotated"),
                        ],
                        default="updated",
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_client_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="otto.apiclient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ApiClientScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=100)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_assignments",
                        to="otto.apiclient",
                    ),
                ),
            ],
            options={
                "ordering": ["scope"],
            },
        ),
        migrations.AddIndex(
            model_name="apiclient",
            index=models.Index(
                fields=["is_active", "name"], name="otto_apicli_is_acti_9a6d70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiclient",
            index=models.Index(
                fields=["owner", "is_active"], name="otto_apicli_owner_i_db9f4f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="apiclientallowedip",
            constraint=models.UniqueConstraint(
                fields=("client", "cidr"), name="otto_api_client_allowed_ip_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="apiclientauditevent",
            index=models.Index(
                fields=["client", "-created_at"], name="otto_apicli_client__f4a28e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiclientauditevent",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="otto_apicli_event_t_933d95_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="apiclientscope",
            constraint=models.UniqueConstraint(
                fields=("client", "scope"), name="otto_api_client_scope_unique"
            ),
        ),
    ]
