# Generated by Django 5.1.1 on 2025-01-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0030_rename_uuid_intake_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Intake",
            new_name="ConciergeRequest",
        ),
    ]
