# Generated by Django 6.0.5 on 2026-06-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otto", "0029_apiclient_apiclientallowedip_apiclientauditevent_and_more"),
        ("otto", "0031_reset_terms_acceptance_for_all_users"),
    ]

    operations = []
