apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
  namespace: otto
spec:
  provider: azure
  secretObjects:
  - secretName: azure-keyvault-secrets
    type: Opaque
    data:
      - key: djangosecretkey
        objectName: DJANGO-SECRET-KEY
      - key: postgrespasswordkey
        objectName: POSTGRES-PASSWORD
      - key: openaiservicekey
        objectName: OPENAI-SERVICE-KEY
      - key: cognitiveservicekey
        objectName: COGNITIVE-SERVICE-KEY
      - key: storageaccountkey
        objectName: STORAGE-KEY
      - key: cosmosdbpasswordkey
        objectName: DATABASE-PASSWORD
      - key: cosmosdbhostnamekey
        objectName: COSMOSDB-HOSTNAME
      - key: entraclientidkey
        objectName: ENTRA-CLIENT-ID
      - key: entraclientsecretkey
        objectName: ENTRA-CLIENT-SECRET
      - key: entraauthoritykey
        objectName: ENTRA-AUTHORITY
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"  # Set to true for system-assigned managed identity
    userAssignedIdentityID: "401ec71d-59e9-4348-9019-99dc5a23b02c"    # Leave empty for system-assigned managed identity
    keyvaultName: "jus-dev-ottoa-adminkv"    
    objects: |
      array:
        - |
          objectName: DJANGO-SECRET-KEY
          objectType: secret       # object types: secret, key, or cert
          objectVersion: ""
        - |
          objectName: POSTGRES-PASSWORD
          objectType: secret       # object types: secret, key, or cert
          objectVersion: ""      
        - |
          objectName: COGNITIVE-SERVICE-KEY
          objectType: secret       # object types: secret, key, or cert
          objectVersion: ""    
        - |
          objectName: OPENAI-SERVICE-KEY
          objectType: secret       # object types: secret, key, or cert
          objectVersion: ""          
        - |
          objectName: STORAGE-KEY
          objectType: secret       # object types: secret, key, or cert
          objectVersion: ""          
        - |
          objectName: DATABASE-PASSWORD
          objectType: secret       # object types: secret, key, or cert
          objectVersion: ""
        - |
          objectName: COSMOSDB-HOSTNAME
          objectType: secret       # object types: secret, key, or cert
          objectVersion: ""
        - |
          objectName: ENTRA-CLIENT-ID
          objectType: secret       # object types: secret, key, or cert
          objectVersion: ""
        - |
          objectName: ENTRA-CLIENT-SECRET
          objectType: secret       # object types: secret, key, or cert
          objectVersion: ""
        - |
          objectName: ENTRA-AUTHORITY
          objectType: secret       # object types: secret, key, or cert
          objectVersion: ""
    tenantId: "44c0b27b-bb8b-4284-829c-8ad96d3b40e5"
