version: '3.8'
services:
  otto-setup:
    image: otto-setup:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otto-setup-container
    volumes:
      - ./:/workspace
    stdin_open: true
    tty: true
