# Generated by Django 5.0.7 on 2024-07-25 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnswerSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_text", models.TextField()),
                ("node_score", models.FloatField(default=0.0)),
                ("saved_citation", models.TextField(blank=True)),
                (
                    "saved_data_source_name",
                    models.CharField(blank=True, max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("eof", models.BooleanField(default=False)),
                ("text", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preset_name", models.CharField(blank=True, max_length=255)),
                ("user_default", models.BooleanField(default=False)),
                ("mode", models.CharField(default="qa", max_length=255)),
                (
                    "chat_model",
                    models.CharField(default="gpt-35-turbo", max_length=255),
                ),
                ("chat_temperature", models.FloatField(default=0.1)),
                (
                    "chat_system_prompt",
                    models.TextField(
                        blank=True,
                        default="You are a general-purpose AI chatbot. You follow these rules:\n\n1. You are professional, accurate and helpful above all.\n\n2. Your name is 'Otto', an AI who works for the Department of Justice Canada.\n\n3. You do not have access to the internet or other knowledge bases. If you are asked about very specific facts, especially one about the Government of Canada or laws, you always caveat your response, e.g., 'I am a pre-trained AI and do not have access to the internet, so my answers might not be correct. Based on my training data, I expect that...'\n\n4. If you are asked a question about Department of Justice or other Government of Canada / HR policies, you inform users of Otto's 'Q&A' mode which can provide more accurate information.\n\n6. You answer in markdown format to provide clear and readable responses.",
                    ),
                ),
                (
                    "summarize_model",
                    models.CharField(default="gpt-35-turbo", max_length=255),
                ),
                ("summarize_style", models.CharField(default="short", max_length=255)),
                ("summarize_language", models.CharField(default="en", max_length=255)),
                ("summarize_prompt", models.TextField(blank=True)),
                ("translate_language", models.CharField(default="fr", max_length=255)),
                ("qa_model", models.CharField(default="gpt-35-turbo", max_length=255)),
                ("qa_topk", models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("feedback", models.IntegerField(default=0)),
                ("feedback_comment", models.TextField(blank=True)),
                ("is_bot", models.BooleanField(default=False)),
                ("bot_name", models.CharField(blank=True, max_length=255)),
                ("cost", models.FloatField(default=0.0)),
                ("pinned", models.BooleanField(default=False)),
                ("details", models.JSONField(default=dict)),
                ("mode", models.CharField(default="chat", max_length=255)),
            ],
        ),
    ]
