# Generated by Django 5.1.5 on 2025-02-12 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnswerSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(blank=True, max_length=255)),
                ("node_score", models.FloatField(default=0.0)),
                ("saved_citation", models.TextField(blank=True)),
                ("group_number", models.IntegerField(default=0)),
                ("min_page", models.IntegerField(null=True)),
                ("max_page", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("eof", models.BooleanField(default=False)),
                ("text", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(default="chat", max_length=255)),
                ("prompt", models.TextField(blank=True, default="")),
                ("chat_model", models.CharField(default="gpt-4o", max_length=255)),
                ("chat_temperature", models.FloatField(default=0.1)),
                ("chat_system_prompt", models.TextField(blank=True)),
                ("chat_agent", models.BooleanField(default=False)),
                ("summarize_model", models.CharField(default="gpt-4o", max_length=255)),
                ("summarize_style", models.CharField(default="short", max_length=255)),
                ("summarize_language", models.CharField(default="en", max_length=255)),
                ("summarize_instructions", models.TextField(blank=True)),
                ("summarize_prompt", models.TextField(blank=True)),
                ("summarize_gender_neutral", models.BooleanField(default=True)),
                ("translate_language", models.CharField(default="fr", max_length=255)),
                ("qa_model", models.CharField(default="gpt-4o", max_length=255)),
                (
                    "qa_mode",
                    models.CharField(
                        choices=[
                            ("rag", "Use top sources only (fast, cheap)"),
                            ("summarize", "Full documents, separate answers ($)"),
                            (
                                "summarize_combined",
                                "Full documents, combined answer ($)",
                            ),
                        ],
                        default="rag",
                        max_length=20,
                    ),
                ),
                (
                    "qa_scope",
                    models.CharField(
                        choices=[
                            ("all", "Entire library"),
                            ("data_sources", "Selected folders"),
                            ("documents", "Selected documents"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("qa_topk", models.IntegerField(default=5)),
                ("qa_system_prompt", models.TextField(blank=True)),
                ("qa_prompt_template", models.TextField(blank=True)),
                ("qa_pre_instructions", models.TextField(blank=True)),
                ("qa_post_instructions", models.TextField(blank=True)),
                (
                    "qa_source_order",
                    models.CharField(
                        choices=[
                            ("score", "Relevance score"),
                            ("reading_order", "Reading order"),
                        ],
                        default="score",
                        max_length=20,
                    ),
                ),
                ("qa_vector_ratio", models.FloatField(default=0.6)),
                ("qa_answer_mode", models.CharField(default="combined", max_length=20)),
                ("qa_prune", models.BooleanField(default=True)),
                ("qa_rewrite", models.BooleanField(default=False)),
                ("qa_granularity", models.IntegerField(default=512)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("feedback", models.IntegerField(default=0)),
                ("feedback_comment", models.TextField(blank=True)),
                ("is_bot", models.BooleanField(default=False)),
                ("bot_name", models.CharField(blank=True, max_length=255)),
                (
                    "usd_cost",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                ("pinned", models.BooleanField(default=False)),
                ("details", models.JSONField(default=dict)),
                ("mode", models.CharField(default="chat", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Preset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(blank=True, max_length=255)),
                ("name_fr", models.CharField(blank=True, max_length=255)),
                ("description_en", models.TextField(blank=True)),
                ("description_fr", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "sharing_option",
                    models.CharField(
                        choices=[
                            ("private", "Make private"),
                            ("everyone", "Share with everyone"),
                            ("others", "Share with others"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("english_default", models.BooleanField(default=False)),
                ("french_default", models.BooleanField(default=False)),
            ],
        ),
    ]
