# Generated by Django 5.1.5 on 2025-02-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["id"]},
        ),
    ]
