# Generated by Django 5.1.5 on 2025-02-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="message",
            name="claims_list",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
