# Generated by Django 5.0.7 on 2024-08-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answersource",
            name="saved_data_source_name",
        ),
    ]
