# Generated by Django 5.1.1 on 2025-02-24 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="chat",
            name="last_message_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
