# Generated by Django 5.0.7 on 2024-08-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_answersource_saved_data_source_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatoptions",
            name="chat_system_prompt",
            field=models.TextField(blank=True),
        ),
    ]
