# Generated by Django 5.1.5 on 2025-02-28 18:35

import django.utils.timezone
from django.db import migrations, models


def set_last_message_date(apps, schema_editor):
    Chat = apps.get_model("chat", "Chat")
    for chat in Chat.objects.all():
        chat.last_message_date = chat.accessed_at
        chat.save()


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_message_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="last_message_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(set_last_message_date),
    ]
