# Generated by Django 5.1.1 on 2025-02-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_chat_options_alter_message_options_and_more"),
        ("chat", "0004_alter_message_options"),
    ]

    operations = []
