# Generated by Django 5.1.5 on 2025-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_answersource_claims_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="answersource",
            name="highlighted_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
