# Generated by Django 5.1.5 on 2025-02-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_answersource_highlighted_text_message_claims_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answersource",
            old_name="highlighted_text",
            new_name="processed_text",
        ),
    ]
