# Generated by Django 5.1.5 on 2025-02-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_answersource_claims_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answersource",
            name="claims_list",
        ),
        migrations.AddField(
            model_name="message",
            name="claims_list",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
