# Generated by Django 5.1 on 2024-08-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_chatoptions_chat_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="qa_prompt",
            field=models.TextField(blank=True),
        ),
    ]
