# Generated by Django 5.1.5 on 2025-02-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_answersource_highlighted_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answersource",
            name="claims_list",
        ),
    ]
