# Generated by Django 5.1.5 on 2025-03-03 17:24

from django.db import migrations
from django.core.management import call_command


def reset_cost_types(apps, schema_editor):
    call_command("reset_app_data", "cost_types")


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_rename_highlighted_text_answersource_processed_text"),
    ]

    operations = [
        migrations.RunPython(reset_cost_types),
    ]
