# Generated by Django 5.1.5 on 2025-03-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chat_last_message_date"),
        ("chat", "0006_rename_highlighted_text_answersource_processed_text"),
    ]

    operations = []
