# Generated by Django 5.1.5 on 2025-03-07 16:51

import django.utils.timezone
from django.db import migrations, models


def set_last_modification_date(apps, schema_editor):
    Chat = apps.get_model("chat", "Chat")
    # Only fetch the fields we need to avoid selecting columns that may not
    # exist anymore in later schemas (e.g., removed FKs).
    for chat in Chat.objects.only("id", "accessed_at").iterator():
        chat.last_modification_date = chat.accessed_at
        chat.save(update_fields=["last_modification_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_rename_highlighted_text_answersource_processed_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="last_modification_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(set_last_modification_date),
    ]
