# Generated by Django 5.1 on 2024-08-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_chatoptions_qa_prompt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatoptions",
            name="qa_prompt",
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_post_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_pre_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_system_prompt",
            field=models.TextField(blank=True),
        ),
    ]
