# Generated by Django 5.1.5 on 2025-03-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_merge_20250305_1937"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="last_message_date",
            new_name="last_modification_date",
        ),
    ]
