# Generated by Django 5.1.5 on 2025-03-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_auto_20250303_1724"),
        ("chat", "0007_chat_last_modification_date"),
    ]

    operations = []
