# Generated by Django 5.1 on 2024-08-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_remove_chatoptions_qa_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="qa_prompt_template",
            field=models.TextField(blank=True),
        ),
    ]
