# Generated by Django 5.1.5 on 2025-03-14 14:19

from django.db import migrations
from django.core.management import call_command


def reset_cost_types(apps, schema_editor):
    call_command("reset_app_data", "presets")


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_merge_20250310_1421"),
        ("librarian", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(reset_cost_types),
    ]
