# Generated by Django 5.1.5 on 2025-04-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_merge_20250310_1421"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preset",
            name="favourited_by",
        ),
    ]
