# Generated by Django 5.1.8 on 2025-04-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_remove_preset_favourited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatfile",
            name="sha256_hash_from_client",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
