# Generated by Django 5.1 on 2024-08-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_chatoptions_qa_prompt_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="qa_answer_mode",
            field=models.CharField(default="combined", max_length=20),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_prune",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_source_order",
            field=models.CharField(default="score", max_length=20),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_vector_ratio",
            field=models.FloatField(default=0.6),
        ),
    ]
