# Generated by Django 5.2 on 2025-05-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_chatfile_sha256_hash_from_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatfile",
            name="sha256_hash_from_client",
        ),
    ]
