# Generated by Django 5.1 on 2024-08-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_chatoptions_qa_answer_mode_chatoptions_qa_prune_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="qa_rewrite",
            field=models.BooleanField(default=False),
        ),
    ]
