# Generated by Django 5.1 on 2024-08-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_chatoptions_qa_rewrite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="cost",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
