# Generated by Django 5.2 on 2025-05-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_remove_chatfile_sha256_hash_from_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatoptions",
            name="summarize_gender_neutral",
        ),
        migrations.RemoveField(
            model_name="chatoptions",
            name="summarize_instructions",
        ),
        migrations.RemoveField(
            model_name="chatoptions",
            name="summarize_language",
        ),
        migrations.RemoveField(
            model_name="chatoptions",
            name="summarize_style",
        ),
    ]
