# Generated by Django 5.1.8 on 2025-07-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_remove_chatoptions_summarize_gender_neutral_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="chat_reasoning_effort",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="chat_model",
            field=models.CharField(default="gpt-4.1-mini", max_length=255),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_model",
            field=models.CharField(default="gpt-4.1-mini", max_length=255),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="summarize_model",
            field=models.CharField(default="gpt-4.1-mini", max_length=255),
        ),
    ]
