# Generated by Django 5.1 on 2024-09-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_rename_cost_message_usd_cost"),
        ("librarian", "0005_rename_cost_document_usd_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="qa_documents",
            field=models.ManyToManyField(
                related_name="qa_options", to="librarian.document"
            ),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_scope",
            field=models.CharField(
                choices=[
                    ("all", "Entire library"),
                    ("data_sources", "Selected data sources"),
                    ("documents", "Selected documents"),
                ],
                default="all",
                max_length=255,
            ),
        ),
    ]
