# Generated by Django 5.1.8 on 2025-07-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_chatoptions_chat_reasoning_effort_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="seconds_elapsed",
            field=models.FloatField(default=0.0),
        ),
    ]
