# Generated by Django 5.1.8 on 2025-07-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_message_seconds_elapsed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatoptions",
            name="chat_reasoning_effort",
            field=models.CharField(
                choices=[
                    ("low", "Low (faster, cheaper)"),
                    ("medium", "Medium (default)"),
                    ("high", "High (slower, more expensive)"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
    ]
