# Generated by Django 5.1 on 2024-09-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_chatoptions_qa_documents_chatoptions_qa_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="chat_agent",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="mode",
            field=models.CharField(default="chat", max_length=255),
        ),
    ]
