# Generated by Django 5.1 on 2024-09-06 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_remove_chatoptions_preset_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preset",
            name="default_for",
        ),
        migrations.AddField(
            model_name="preset",
            name="default_for",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_preset",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
