# Generated by Django 5.1.8 on 2025-07-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_alter_chatoptions_chat_reasoning_effort"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_mode",
            field=models.CharField(
                choices=[
                    ("rag", "Use top sources only (fast, cheap)"),
                    ("summarize", "Full documents, separate answers ($)"),
                    ("summarize_combined", "Full documents, combined answer ($)"),
                    ("rag_per_doc", "Use top sources for each selected document"),
                ],
                default="rag",
                max_length=20,
            ),
        ),
    ]
