# Generated by Django 5.1.8 on 2025-07-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_alter_chatoptions_chat_reasoning_effort"),
    ]

    def migrate_chatoptions_data(apps, schema_editor):
        ChatOptions = apps.get_model("chat", "ChatOptions")
        # Use .all() to iterate over all ChatOptions objects
        for obj in ChatOptions.objects.all():
            # --- Migrate qa_granular_toggle from old qa_answer_mode ---
            # Default to False if not present
            qa_answer_mode = getattr(obj, "qa_answer_mode", None)
            if qa_answer_mode == "per-source":
                obj.qa_granular_toggle = True
            else:
                obj.qa_granular_toggle = False

            # --- Migrate qa_mode and qa_process_mode ---
            old_qa_mode = getattr(obj, "qa_mode", None)
            if old_qa_mode == "rag":
                obj.qa_mode = "rag"
                obj.qa_process_mode = "combined_docs"
            elif old_qa_mode == "summarize":
                obj.qa_mode = "summarize"
                obj.qa_process_mode = "per_doc"
            elif old_qa_mode == "summarize_combined":
                obj.qa_mode = "summarize"
                obj.qa_process_mode = "combined_docs"
            # else: leave as is (should not happen)
            obj.save(update_fields=["qa_granular_toggle", "qa_mode", "qa_process_mode"])

    operations = [
        migrations.RemoveField(
            model_name="chatoptions",
            name="qa_answer_mode",
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_granular_toggle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_process_mode",
            field=models.CharField(
                choices=[("combined_docs", "Combine"), ("per_doc", "Separate")],
                default="combined_docs",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_mode",
            field=models.CharField(
                choices=[("rag", "Top excerpts"), ("summarize", "Full documents")],
                default="rag",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            migrate_chatoptions_data, reverse_code=migrations.RunPython.noop
        ),
    ]
