# Generated by Django 5.1 on 2024-09-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_remove_preset_default_for_preset_default_for"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preset",
            name="default_for",
        ),
    ]
