# Generated by Django 5.1.8 on 2025-07-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_alter_chatoptions_chat_reasoning_effort"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatoptions",
            name="qa_answer_mode",
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_answer_type",
            field=models.CharField(
                choices=[
                    ("whole_library", "Across whole library"),
                    ("per_doc", "Separately for each document"),
                ],
                default="whole_library",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_granular_toggle",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_mode",
            field=models.CharField(
                choices=[
                    ("rag", "Use top sources only (fast, cheap)"),
                    ("summarize", "Use full documents ($)"),
                ],
                default="rag",
                max_length=20,
            ),
        ),
    ]
