# Generated by Django 5.1.8 on 2025-07-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_alter_chatoptions_chat_reasoning_effort"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatoptions",
            name="chat_agent",
        ),
    ]
