# Generated by Django 5.1.8 on 2025-07-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_remove_chatoptions_chat_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="agent_model",
            field=models.CharField(default="gpt-4.1-mini", max_length=255),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="agent_tools",
            field=models.JSONField(default=list),
        ),
    ]
