# Generated by Django 5.1.8 on 2025-08-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_remove_chatoptions_qa_answer_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="security_label",
        ),
    ]
