# Generated by Django 5.1.8 on 2025-07-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_remove_chatoptions_qa_answer_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_answer_type",
            field=models.CharField(
                choices=[
                    ("combined_docs", "Pool documents together"),
                    ("per_doc", "Each document separately ($)"),
                ],
                default="combined_docs",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_mode",
            field=models.CharField(
                choices=[
                    ("combined_docs", "Top sources only (fast, cheap)"),
                    ("per_doc", "Full documents ($)"),
                ],
                default="rag",
                max_length=20,
            ),
        ),
    ]
