# Generated by Django 5.1.8 on 2025-08-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_remove_chatoptions_qa_answer_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="pinned",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
