# Generated by Django 5.1 on 2024-09-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_chat_data_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="qa_mode",
            field=models.CharField(
                choices=[
                    ("rag", "Use top sources only (fast, cheap)"),
                    ("summarize", "Read entire documents (slow, expensive)"),
                ],
                default="rag",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_scope",
            field=models.CharField(
                choices=[
                    ("all", "Entire library"),
                    ("data_sources", "Selected data sources"),
                    ("documents", "Selected documents"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
