# Generated by Django 5.1 on 2024-09-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_chatoptions_qa_documents_chatoptions_qa_scope"),
        ("chat", "0016_remove_preset_default_for"),
    ]

    operations = []
