# Generated by Django 5.1 on 2024-09-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_chatoptions_qa_mode_alter_chatoptions_qa_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_source_order",
            field=models.CharField(
                choices=[
                    ("score", "Relevance score"),
                    ("reading_order", "Reading order"),
                ],
                default="score",
                max_length=20,
            ),
        ),
    ]
