# Generated by Django 5.1.8 on 2025-08-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_chat_pinned"),
        ("chat", "0017_remove_chat_security_label"),
    ]

    operations = []
