# Generated by Django 5.1 on 2024-09-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_chat_data_source"),
        ("chat", "0017_merge_20240923_1714"),
    ]

    operations = []
