# Generated by Django 5.1.8 on 2025-07-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_remove_chatoptions_qa_answer_mode_and_more"),
        ("chat", "0017_chatoptions_agent_model_chatoptions_agent_tools"),
    ]

    operations = []
