# Generated by Django 5.1 on 2024-10-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_alter_chatoptions_qa_source_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="qa_granularity",
            field=models.IntegerField(default=768),
        ),
    ]
