# Generated by Django 5.1 on 2024-10-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_alter_chatoptions_qa_source_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="parent",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child",
                to="chat.message",
            ),
        ),
    ]
