# Generated by Django 5.2.5 on 2025-08-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_merge_20250815_1540"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="translate_method",
            field=models.CharField(
                choices=[
                    ("azure", "Azure Translator"),
                    ("gpt", "GPT-4.1 (alternative method)"),
                ],
                default="azure",
                max_length=20,
            ),
        ),
    ]
