# Generated by Django 5.1.8 on 2025-09-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_merge_20250815_1540"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="translate_model",
            field=models.CharField(
                choices=[
                    ("azure_custom", "Azure Translator (JUS custom)"),
                    ("azure", "Azure Translator (standard)"),
                    ("gpt", "GPT-4.1-mini"),
                ],
                default="azure_custom",
                max_length=20,
            ),
        ),
    ]
