# Generated by Django 5.1.8 on 2025-07-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_merge_20250725_2319"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="agent_type",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
