# Generated by Django 5.1.8 on 2025-09-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_chatoptions_translate_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="translation_glossary",
            field=models.FileField(blank=True, null=True, upload_to="glossaries/"),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="translate_model",
            field=models.CharField(default="azure_custom", max_length=20),
        ),
    ]
