# Generated by Django 5.1.8 on 2025-09-09 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_chatoptions_translate_model"),
        ("librarian", "0004_alter_document_pdf_extraction_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="translation_glossary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="glossary_options",
                to="librarian.savedfile",
            ),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="translate_model",
            field=models.CharField(default="azure_custom", max_length=20),
        ),
    ]
