# Generated by Django 5.1.8 on 2025-07-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_chatoptions_agent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatoptions",
            name="agent_type",
            field=models.CharField(
                blank=True, default="tool_calling_agent", max_length=40
            ),
        ),
    ]
