# Generated by Django 5.1 on 2024-10-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_chatoptions_qa_granularity"),
    ]

    operations = [
        migrations.AddField(
            model_name="answersource",
            name="group_number",
            field=models.IntegerField(default=0),
        ),
    ]
