# Generated by Django 5.1 on 2024-10-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_alter_message_parent"),
        ("chat", "0020_answersource_group_number"),
    ]

    operations = []
