# Generated by Django 5.1.8 on 2025-09-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0020_add_translation_glossary_savedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="translate_prompt",
            field=models.TextField(blank=True),
        ),
    ]
