# Generated by Django 5.1.8 on 2025-09-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0021_chatoptions_translate_prompt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatoptions",
            old_name="translation_glossary",
            new_name="translate_glossary",
        ),
    ]
