# Generated by Django 5.1 on 2024-10-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_remove_chatoptions_preset_name_and_more"),
        ("chat", "0021_merge_20241008_1956"),
    ]

    operations = []
