# Generated by Django 5.1.8 on 2025-09-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0022_rename_translation_glossary_chatoptions_translate_glossary"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="translate_glossary_filename",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
