# Generated by Django 5.1 on 2024-10-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0022_remove_chat_data_source_remove_chat_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answersource",
            name="max_page",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="answersource",
            name="min_page",
            field=models.IntegerField(null=True),
        ),
    ]
