# Generated by Django 5.1 on 2024-10-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0022_merge_20241010_1557"),
        ("chat", "0022_remove_chat_data_source_remove_chat_options_and_more"),
    ]

    operations = []
