# Generated by Django 5.1 on 2024-10-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0023_merge_20241011_1541"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preset",
            name="editable_by",
        ),
        migrations.AddField(
            model_name="preset",
            name="sharing_option",
            field=models.CharField(
                choices=[
                    ("everyone", "Share with everyone"),
                    ("others", "Share with others"),
                ],
                default="others",
                max_length=10,
            ),
        ),
    ]
