# Generated by Django 5.1.8 on 2025-09-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0023_add_translate_glossary_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="qa_reasoning_effort",
            field=models.CharField(
                choices=[
                    ("minimal", "Minimal (fastest, cheapest)"),
                    ("low", "Low (faster, cheaper)"),
                    ("medium", "Medium (default)"),
                    ("high", "High (slower, more expensive)"),
                ],
                default="minimal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="chat_reasoning_effort",
            field=models.CharField(
                choices=[
                    ("minimal", "Minimal (fastest, cheapest)"),
                    ("low", "Low (faster, cheaper)"),
                    ("medium", "Medium (default)"),
                    ("high", "High (slower, more expensive)"),
                ],
                default="minimal",
                max_length=10,
            ),
        ),
    ]
