# Generated by Django 5.1 on 2024-10-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0024_remove_preset_editable_by_preset_sharing_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="sharing_option",
            field=models.CharField(
                choices=[
                    ("private", "Make Private"),
                    ("everyone", "Share with everyone"),
                    ("others", "Share with others"),
                ],
                default="others",
                max_length=10,
            ),
        ),
    ]
