# Generated by Django 5.2.5 on 2025-09-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0024_chatoptions_qa_reasoning_effort_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatoptions",
            name="chat_reasoning_effort",
            field=models.CharField(
                choices=[
                    ("minimal", "Minimal (fastest, cheapest)"),
                    ("low", "Low (better instruction-following)"),
                    ("medium", "Medium (more deliberate reasoning)"),
                    ("high", "High (complex, multi-step reasoning)"),
                ],
                default="minimal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_reasoning_effort",
            field=models.CharField(
                choices=[
                    ("minimal", "Minimal (fastest, cheapest)"),
                    ("low", "Low (better instruction-following)"),
                    ("medium", "Medium (more deliberate reasoning)"),
                    ("high", "High (complex, multi-step reasoning)"),
                ],
                default="minimal",
                max_length=10,
            ),
        ),
    ]
