# Generated by Django 5.2.5 on 2025-10-06 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0025_alter_chatoptions_chat_reasoning_effort_and_more"),
        ("librarian", "0008_alter_document_data_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatfile",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_files",
                to="librarian.document",
            ),
        ),
    ]
