# Generated by Django 5.1 on 2024-10-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0023_answersource_max_page_answersource_min_page"),
        ("chat", "0026_alter_preset_sharing_option"),
    ]

    operations = []
