# Generated by Django 5.2.5 on 2025-10-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0026_chatfile_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatfile",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
