# Generated by Django 5.1 on 2024-10-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0027_merge_20241025_2046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="sharing_option",
            field=models.CharField(choices=[], default="private", max_length=10),
        ),
    ]
