# Generated by Django 5.2.5 on 2025-10-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0027_alter_chatfile_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatfile",
            name="text",
        ),
    ]
