# Generated by Django 5.2.5 on 2025-10-17 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0028_remove_chatfile_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="preset",
            name="editable_by",
            field=models.ManyToManyField(
                blank=True, related_name="editable_presets", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
