# Generated by Django 5.2.8 on 2025-11-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0029_preset_editable_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatoptions",
            name="chat_temperature",
            field=models.FloatField(default=0.5),
        ),
    ]
