# Generated by Django 5.2.8 on 2025-11-10 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0029_preset_editable_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["user", "-last_modification_date"],
                name="chat_chat_user_id_4f3805_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["user", "title"], name="chat_chat_user_id_374e83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "date_created"], name="chat_messag_chat_id_dece50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "is_bot"], name="chat_messag_chat_id_4fe45b_idx"
            ),
        ),
    ]
