# Generated by Django 5.1 on 2024-10-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0029_remove_preset_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="sharing_option",
            field=models.CharField(
                choices=[
                    ("private", "Make Private"),
                    ("everyone", "Share with everyone"),
                    ("others", "Share with others"),
                ],
                default="private",
                max_length=10,
            ),
        ),
    ]
