# Generated by Django 5.1.1 on 2024-11-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0030_alter_preset_sharing_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="sharing_option",
            field=models.CharField(
                choices=[
                    ("private", "Make private"),
                    ("everyone", "Share with everyone"),
                    ("others", "Share with others"),
                ],
                default="private",
                max_length=10,
            ),
        ),
    ]
