# Generated by Django 5.2.8 on 2025-11-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0030_alter_chatoptions_chat_temperature"),
        ("chat", "0030_chat_chat_chat_user_id_4f3805_idx_and_more"),
    ]

    operations = []
