# Generated by Django 5.2.8 on 2025-11-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0031_merge_20251113_1622"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="summarize_reasoning_effort",
            field=models.CharField(
                choices=[
                    ("minimal", "Minimal (fastest, cheapest)"),
                    ("low", "Low (better instruction-following)"),
                    ("medium", "Medium (more deliberate reasoning)"),
                    ("high", "High (complex, multi-step reasoning)"),
                ],
                default="minimal",
                max_length=10,
            ),
        ),
    ]
