# Generated by Django 5.1.1 on 2024-11-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0032_chatoptions_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatoptions",
            name="prompt",
            field=models.TextField(blank=True, default=""),
        ),
    ]
