# Generated by Django 5.2.8 on 2025-11-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0032_chatoptions_summarize_reasoning_effort"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="qa_history",
            field=models.BooleanField(default=True),
        ),
    ]
