# Generated by Django 5.1.1 on 2024-11-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0033_alter_chatoptions_prompt"),
        ("chat", "0033_alter_message_usd_cost"),
    ]

    operations = []
