# Generated by Django 5.2.8 on 2025-11-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0033_chatoptions_qa_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatoptions",
            name="qa_rewrite",
        ),
    ]
