# Generated by Django 5.2.8 on 2025-11-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0034_remove_chatoptions_qa_rewrite"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="chat_verbosity",
            field=models.CharField(
                choices=[
                    ("low", "Low (concise responses)"),
                    ("medium", "Medium (balanced detail)"),
                    ("high", "High (detailed responses)"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_verbosity",
            field=models.CharField(
                choices=[
                    ("low", "Low (concise responses)"),
                    ("medium", "Medium (balanced detail)"),
                    ("high", "High (detailed responses)"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="summarize_verbosity",
            field=models.CharField(
                choices=[
                    ("low", "Low (concise responses)"),
                    ("medium", "Medium (balanced detail)"),
                    ("high", "High (detailed responses)"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_history",
            field=models.BooleanField(default=False),
        ),
    ]
