# Generated by Django 5.1.1 on 2024-11-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0034_chatoptions_summarize_gender_neutral"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="summarize_instructions",
            field=models.TextField(blank=True),
        ),
    ]
