# Generated by Django 5.1.1 on 2024-11-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0034_merge_20241112_2042"),
        ("chat", "0035_chatoptions_summarize_instructions"),
    ]

    operations = []
