# Generated by Django 5.2.9 on 2025-12-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0035_chatoptions_chat_verbosity_chatoptions_qa_verbosity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_mode",
            field=models.CharField(
                choices=[
                    ("rag", "Top excerpts (RAG)"),
                    ("summarize", "Full documents"),
                ],
                default="rag",
                max_length=20,
            ),
        ),
    ]
