# Generated by Django 5.1.1 on 2024-11-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0036_merge_20241113_2222"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answersource",
            name="node_text",
        ),
        migrations.AddField(
            model_name="answersource",
            name="node_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
