# Generated by Django 5.2.9 on 2026-01-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0036_alter_chatoptions_qa_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatoptions",
            name="chat_model",
            field=models.CharField(default="gpt-5.1", max_length=255),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="chat_reasoning_effort",
            field=models.CharField(
                choices=[
                    ("none", "None (fastest, cheapest)"),
                    ("minimal", "Minimal (fastest, cheapest)"),
                    ("low", "Low (better instruction-following)"),
                    ("medium", "Medium (more deliberate reasoning)"),
                    ("high", "High (complex, multi-step reasoning)"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_model",
            field=models.CharField(default="gpt-5-mini", max_length=255),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_reasoning_effort",
            field=models.CharField(
                choices=[
                    ("none", "None (fastest, cheapest)"),
                    ("minimal", "Minimal (fastest, cheapest)"),
                    ("low", "Low (better instruction-following)"),
                    ("medium", "Medium (more deliberate reasoning)"),
                    ("high", "High (complex, multi-step reasoning)"),
                ],
                default="minimal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="summarize_model",
            field=models.CharField(default="gpt-5-mini", max_length=255),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="summarize_reasoning_effort",
            field=models.CharField(
                choices=[
                    ("none", "None (fastest, cheapest)"),
                    ("minimal", "Minimal (fastest, cheapest)"),
                    ("low", "Low (better instruction-following)"),
                    ("medium", "Medium (more deliberate reasoning)"),
                    ("high", "High (complex, multi-step reasoning)"),
                ],
                default="minimal",
                max_length=10,
            ),
        ),
    ]
