# Generated by Django 5.2.9 on 2026-01-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0037_alter_chatoptions_chat_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="chat_include_images",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="chat_include_pdfs",
            field=models.BooleanField(default=False),
        ),
    ]
