# Generated by Django 5.2.9 on 2026-01-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0038_add_chat_include_images_pdfs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatoptions",
            name="qa_prune",
        ),
    ]
