# Generated by Django 5.1.1 on 2024-11-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0038_alter_chatoptions_qa_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_mode",
            field=models.CharField(
                choices=[
                    ("rag", "Use top sources only (fast, cheap)"),
                    ("summarize", "Full documents, separate answers ($)"),
                    (
                        "summarize_combined",
                        "Full documents, combined answer ($)",
                    ),
                ],
                default="rag",
                max_length=20,
            ),
        ),
    ]
