# Generated by Django 5.1.1 on 2024-11-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0039_alter_chatoptions_qa_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatfile",
            name="filename",
            field=models.CharField(max_length=500),
        ),
    ]
