# Generated by Django 5.2.11 on 2026-03-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0039_remove_qa_prune"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatoptions",
            name="chat_agent",
        ),
    ]
