# Generated by Django 5.1.1 on 2024-12-02 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0040_alter_chatfile_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="loaded_preset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat.preset",
            ),
        ),
    ]
