# Generated by Django 6.0.3 on 2026-03-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0040_remove_chatoptions_chat_agent"),
        ("otto", "0023_team_teammembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="preset",
            name="accessible_to_teams",
            field=models.ManyToManyField(
                blank=True, related_name="accessible_presets", to="otto.team"
            ),
        ),
        migrations.AddField(
            model_name="preset",
            name="editable_by_teams",
            field=models.ManyToManyField(
                blank=True, related_name="editable_presets", to="otto.team"
            ),
        ),
    ]
