# Generated by Django 6.0.3 on 2026-04-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0041_preset_accessible_to_teams_preset_editable_by_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatoptions",
            name="chat_reasoning_effort",
            field=models.CharField(
                choices=[
                    ("none", "None (fastest, cheapest)"),
                    ("minimal", "Minimal (fastest, cheapest)"),
                    ("low", "Low (better instruction-following)"),
                    ("medium", "Medium (more deliberate reasoning)"),
                    ("high", "High (complex, multi-step reasoning)"),
                    ("xhigh", "Xhigh (deepest reasoning, slowest)"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_reasoning_effort",
            field=models.CharField(
                choices=[
                    ("none", "None (fastest, cheapest)"),
                    ("minimal", "Minimal (fastest, cheapest)"),
                    ("low", "Low (better instruction-following)"),
                    ("medium", "Medium (more deliberate reasoning)"),
                    ("high", "High (complex, multi-step reasoning)"),
                    ("xhigh", "Xhigh (deepest reasoning, slowest)"),
                ],
                default="minimal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="summarize_reasoning_effort",
            field=models.CharField(
                choices=[
                    ("none", "None (fastest, cheapest)"),
                    ("minimal", "Minimal (fastest, cheapest)"),
                    ("low", "Low (better instruction-following)"),
                    ("medium", "Medium (more deliberate reasoning)"),
                    ("high", "High (complex, multi-step reasoning)"),
                    ("xhigh", "Xhigh (deepest reasoning, slowest)"),
                ],
                default="minimal",
                max_length=10,
            ),
        ),
    ]
