# Generated by Django 5.1.4 on 2025-01-10 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0041_chat_loaded_preset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="preset",
            name="english_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="preset",
            name="french_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="chat_agent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="preset",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
