# Generated by Django 5.1.1 on 2024-12-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0041_chat_loaded_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="chat_system_prompt_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="chat_system_prompt_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_post_instructions_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_post_instructions_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_pre_instructions_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_pre_instructions_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_prompt_template_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_prompt_template_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_system_prompt_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="qa_system_prompt_fr",
            field=models.TextField(blank=True, null=True),
        ),
    ]
