# Generated by Django 5.1.4 on 2025-01-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0042_preset_global_default_alter_chatoptions_chat_agent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preset",
            old_name="global_default",
            new_name="english_default",
        ),
        migrations.AddField(
            model_name="preset",
            name="french_default",
            field=models.BooleanField(default=False),
        ),
    ]
