# Generated by Django 5.1.4 on 2025-01-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0042_preset_english_default_preset_french_default_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatoptions",
            name="qa_scope",
            field=models.CharField(
                choices=[
                    ("all", "Entire library"),
                    ("data_sources", "Selected folders"),
                    ("documents", "Selected documents"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
