# Generated by Django 5.1.1 on 2024-12-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0043_alter_preset_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="summarize_instructions_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="summarize_instructions_fr",
            field=models.TextField(blank=True, null=True),
        ),
    ]
