# Generated by Django 5.1.1 on 2025-01-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0044_chatoptions_summarize_instructions_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preset",
            name="global_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="chat_agent",
            field=models.BooleanField(default=False),
        ),
    ]
