# Generated by Django 5.2.9 on 2026-01-12 19:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("librarian", "0016_datasource_librarian_d_order_97bb87_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                ("pinned", models.BooleanField(default=False, null=True)),
                (
                    "last_modification_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_next_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(blank=True, default="")),
                ("chat_model", models.CharField(default="gpt-5.1", max_length=255)),
                ("chat_temperature", models.FloatField(default=0.5)),
                (
                    "chat_reasoning_effort",
                    models.CharField(
                        choices=[
                            ("none", "None (fastest, cheapest)"),
                            ("minimal", "Minimal (fastest, cheapest)"),
                            ("low", "Low (better instruction-following)"),
                            ("medium", "Medium (more deliberate reasoning)"),
                            ("high", "High (complex, multi-step reasoning)"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "chat_verbosity",
                    models.CharField(
                        choices=[
                            ("low", "Low (concise responses)"),
                            ("medium", "Medium (balanced detail)"),
                            ("high", "High (detailed responses)"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("chat_system_prompt", models.TextField(blank=True)),
                ("chat_include_images", models.BooleanField(default=False)),
                ("chat_include_pdfs", models.BooleanField(default=False)),
                (
                    "chat",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="chat_next.chat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("feedback", models.IntegerField(default=0)),
                ("feedback_comment", models.TextField(blank=True)),
                ("is_bot", models.BooleanField(default=False)),
                ("bot_name", models.CharField(blank=True, max_length=255)),
                (
                    "usd_cost",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                ("details", models.JSONField(default=dict)),
                ("seconds_elapsed", models.FloatField(default=0.0)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat_next.chat",
                    ),
                ),
                (
                    "parent",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child",
                        to="chat_next.message",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ChatFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("eof", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_next_files",
                        to="librarian.document",
                    ),
                ),
                (
                    "saved_file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_next_files",
                        to="librarian.savedfile",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="chat_next.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Preset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(blank=True, max_length=255)),
                ("name_fr", models.CharField(blank=True, max_length=255)),
                ("description_en", models.TextField(blank=True)),
                ("description_fr", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "sharing_option",
                    models.CharField(
                        choices=[
                            ("private", "Make private"),
                            ("everyone", "Share with everyone"),
                            ("others", "Share with others"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("english_default", models.BooleanField(default=False)),
                ("french_default", models.BooleanField(default=False)),
                (
                    "accessible_to",
                    models.ManyToManyField(
                        related_name="chat_next_accessible_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editable_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="chat_next_editable_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "options",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preset",
                        to="chat_next.chatoptions",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_next_preset_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chat",
            name="loaded_preset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat_next.preset",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "date_created"], name="chat_next_m_chat_id_96c258_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "is_bot"], name="chat_next_m_chat_id_42c4fb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("parent__isnull", False), ("is_bot", True)),
                    ("parent__isnull", True),
                    _connector="OR",
                ),
                name="chat_next_check_parent_is_user_message",
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["user", "-last_modification_date"],
                name="chat_next_c_user_id_008be1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["user", "title"], name="chat_next_c_user_id_df3e81_idx"
            ),
        ),
    ]
