# Generated by Django 5.2.9 on 2026-01-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="response_output",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
