# Generated by Django 5.2.9 on 2026-01-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0002_add_response_output_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="chat_enabled_tools",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
