# Generated by Django 5.2.9 on 2026-01-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0003_add_chat_enabled_tools"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="response_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
