# Generated by Django 5.2.9 on 2026-01-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0005_chat_code_interpreter_container_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="chat_auto_approve_tools",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
