# Generated by Django 5.2.9 on 2026-02-09 00:00

from django.db import migrations, models
from django.db.utils import OperationalError, ProgrammingError


def normalize_reasoning_effort(apps, schema_editor):
    """Backfill legacy reasoning effort values when ChatOptions still exists."""

    try:
        ChatOptions = apps.get_model("chat_next", "ChatOptions")
    except LookupError:
        # ChatOptions was removed in later migrations; nothing to normalize.
        return

    table_name = ChatOptions._meta.db_table
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        existing_tables = connection.introspection.table_names(cursor)

    if table_name not in existing_tables:
        # Some environments may already have the table dropped (e.g., partial
        # schema resets). Skip the update rather than raising an error.
        return

    try:
        ChatOptions.objects.filter(
            chat_reasoning_effort__in=["none", "minimal"]
        ).update(chat_reasoning_effort="low")
    except (ProgrammingError, OperationalError) as exc:
        # If the table truly doesn't exist (common when test DBs reuse a schema
        # that has already applied ChatSettings-only migrations), swallow the
        # error so the rest of the migration chain can continue. Re-raise other
        # unexpected errors.
        message = str(getattr(exc, "args", [""])[0])
        if "chat_next_chatoptions" not in message:
            raise



class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0006_add_auto_approve_tools"),
    ]

    operations = [
        migrations.RunPython(
            normalize_reasoning_effort, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="chatoptions",
            name="chat_reasoning_effort",
            field=models.CharField(
                choices=[
                    ("low", "Low (better instruction-following)"),
                    ("medium", "Medium (more deliberate reasoning)"),
                    ("high", "High (complex, multi-step reasoning)"),
                ],
                default="low",
                max_length=10,
            ),
        ),
    ]
