# Generated by Django 5.2.11 on 2026-03-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0007_update_reasoning_effort_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatoptions",
            name="chat_reasoning_effort",
            field=models.CharField(
                choices=[
                    ("none", "None (fastest, cheapest)"),
                    ("minimal", "Minimal (fastest, cheapest)"),
                    ("low", "Low (better instruction-following)"),
                    ("medium", "Medium (more deliberate reasoning)"),
                    ("high", "High (complex, multi-step reasoning)"),
                ],
                default="low",
                max_length=10,
            ),
        ),
    ]
