# Generated by Django 5.2.11 on 2026-03-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0008_alter_chatoptions_chat_reasoning_effort"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="chat_default_context_hints",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
