# Generated by Django 5.2.9 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0009_add_context_hints_to_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatoptions",
            name="chat_max_iterations",
            field=models.PositiveIntegerField(default=25),
        ),
    ]
