# Generated by Django 6.0.3 on 2026-03-18 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0010_chatoptions_chat_max_iterations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Hyphen-case identifier, e.g. 'translate-workflow'",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("display_name_en", models.CharField(max_length=255, null=True)),
                ("display_name_fr", models.CharField(max_length=255, null=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Trigger text: what does this skill do and when to use it."
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        help_text="Trigger text: what does this skill do and when to use it.",
                        null=True,
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        help_text="Trigger text: what does this skill do and when to use it.",
                        null=True,
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Optional short description for card display.",
                        max_length=255,
                    ),
                ),
                (
                    "short_description_en",
                    models.CharField(
                        blank=True,
                        help_text="Optional short description for card display.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "short_description_fr",
                    models.CharField(
                        blank=True,
                        help_text="Optional short description for card display.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Markdown instructions. Aim for under 500 lines / 5000 chars."
                    ),
                ),
                (
                    "body_en",
                    models.TextField(
                        help_text="Markdown instructions. Aim for under 500 lines / 5000 chars.",
                        null=True,
                    ),
                ),
                (
                    "body_fr",
                    models.TextField(
                        help_text="Markdown instructions. Aim for under 500 lines / 5000 chars.",
                        null=True,
                    ),
                ),
                (
                    "required_tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Tool categories to auto-enable, e.g. ["local_terminology"]',
                    ),
                ),
                (
                    "context_hints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Libraries/docs to hint, e.g. [{"type":"library","id":"123","name":"..."}]',
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Free-form tags, e.g. ["translation", "bilingual"]',
                    ),
                ),
                (
                    "sharing_option",
                    models.CharField(
                        choices=[
                            ("private", "Make private"),
                            ("everyone", "Share with everyone"),
                            ("others", "Share with others"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
                ("is_curated", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accessible_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="accessible_chat_next_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editable_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="editable_chat_next_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_chat_next_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="chatoptions",
            name="chat_available_skills",
            field=models.ManyToManyField(
                blank=True, related_name="active_in_options", to="chat_next.skill"
            ),
        ),
    ]
