# Generated by Django 6.0.3 on 2026-03-19 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0011_skill_chatoptions_chat_available_skills"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_display_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name (auto-populated from Entra)",
                        max_length=255,
                    ),
                ),
                ("send_name_to_model", models.BooleanField(default=True)),
                ("job_description", models.TextField(blank=True)),
                ("global_instructions", models.TextField(blank=True)),
                ("chat_model", models.CharField(default="gpt-5.1", max_length=255)),
                ("chat_temperature", models.FloatField(default=0.5)),
                (
                    "chat_reasoning_effort",
                    models.CharField(
                        choices=[
                            ("none", "None (fastest, cheapest)"),
                            ("minimal", "Minimal (fastest, cheapest)"),
                            ("low", "Low (better instruction-following)"),
                            ("medium", "Medium (more deliberate reasoning)"),
                            ("high", "High (complex, multi-step reasoning)"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "chat_verbosity",
                    models.CharField(
                        choices=[
                            ("low", "Low (concise responses)"),
                            ("medium", "Medium (balanced detail)"),
                            ("high", "High (detailed responses)"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("chat_enabled_tools", models.JSONField(blank=True, default=list)),
                ("chat_auto_approve_tools", models.JSONField(blank=True, default=list)),
                ("chat_max_iterations", models.PositiveIntegerField(default=25)),
                ("chat_system_prompt", models.TextField(blank=True)),
                ("chat_include_images", models.BooleanField(default=False)),
                ("chat_include_pdfs", models.BooleanField(default=False)),
                (
                    "enabled_skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="enabled_in_settings",
                        to="chat_next.skill",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Chat settings",
            },
        ),
    ]
