# Generated by Django 6.0.3 on 2026-03-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0012_add_chat_settings"),
        ("otto", "0021_remove_feedback_loaded_preset_next_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preset",
            name="options",
        ),
        migrations.RemoveField(
            model_name="preset",
            name="accessible_to",
        ),
        migrations.RemoveField(
            model_name="preset",
            name="editable_by",
        ),
        migrations.RemoveField(
            model_name="preset",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="loaded_preset",
        ),
        migrations.DeleteModel(
            name="ChatOptions",
        ),
        migrations.DeleteModel(
            name="Preset",
        ),
    ]
