# Generated by Django 6.0.3 on 2026-03-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat_next",
            "0013_remove_preset_options_remove_preset_accessible_to_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("name_en", models.CharField(max_length=64, null=True, unique=True)),
                ("name_fr", models.CharField(max_length=64, null=True, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="skill",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Legacy free-form tags (deprecated, use skill_tags M2M).",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="skill_tags",
            field=models.ManyToManyField(
                blank=True, related_name="skills", to="chat_next.skilltag"
            ),
        ),
    ]
