# Generated by ChatGPT on 2026-03-20

from django.db import migrations


DEFAULT_ENABLED_TOOLS = [
    "local_qa_libraries",
    "code_interpreter",
    "local_legal_research",
    "local_document_processing",
    "local_terminology",
]


def backfill_chat_settings_defaults(apps, schema_editor):
    ChatSettings = apps.get_model("chat_next", "ChatSettings")
    Skill = apps.get_model("chat_next", "Skill")

    # Keep this historical data migration independent from fields removed in
    # later schema changes. Fresh CI databases can replay this migration against
    # a database whose table shape was prepared outside the normal linear path,
    # so avoid filtering on columns such as `is_deleted` that no longer exist in
    # newer branches.
    default_skills = list(
        Skill.objects.filter(
            owner__isnull=True,
            sharing_option="everyone",
        ).values_list("id", flat=True)
    )

    for settings in ChatSettings.objects.all():
        if not settings.chat_enabled_tools:
            settings.chat_enabled_tools = list(DEFAULT_ENABLED_TOOLS)
            settings.save(update_fields=["chat_enabled_tools"])

        if default_skills and not settings.enabled_skills.exists():
            settings.enabled_skills.add(*default_skills)


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0014_skill_tag_model"),
    ]

    operations = [
        migrations.RunPython(
            backfill_chat_settings_defaults,
            migrations.RunPython.noop,
        ),
    ]
