# Generated by Django 6.0.3 on 2026-03-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0017_skill_load_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="is_curated",
            new_name="is_featured",
        ),
    ]
