# Generated by Django 6.0.3 on 2026-03-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0018_rename_is_curated_to_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="skilltag",
            name="embedding",
            field=models.JSONField(
                blank=True,
                help_text="Precomputed embedding vector for similarity-based tag suggestions.",
                null=True,
            ),
        ),
    ]
