# Generated by Django 6.0.3 on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0019_add_embedding_to_skilltag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsettings",
            name="send_name_to_model",
            field=models.BooleanField(default=False),
        ),
    ]
