# Generated by Django 6.0.3 on 2026-03-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0020_alter_chatsettings_send_name_to_model_default"),
        ("otto", "0023_team_teammembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="accessible_to_teams",
            field=models.ManyToManyField(
                blank=True, related_name="accessible_chat_next_skills", to="otto.team"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="editable_by_teams",
            field=models.ManyToManyField(
                blank=True, related_name="editable_chat_next_skills", to="otto.team"
            ),
        ),
    ]
