# Generated by Django 6.0.3 on 2026-04-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0021_skill_accessible_to_teams_skill_editable_by_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsettings",
            name="chat_model",
            field=models.CharField(default="gpt-5.4", max_length=255),
        ),
        migrations.AlterField(
            model_name="chatsettings",
            name="chat_reasoning_effort",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("minimal", "Minimal"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("xhigh", "Xhigh"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chatsettings",
            name="chat_verbosity",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
    ]
