# Generated by Django 6.0.3 on 2026-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0022_alter_chatsettings_chat_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsettings",
            name="chat_model",
            field=models.CharField(default="gpt-5.4-mini", max_length=255),
        ),
    ]
