# Generated by Django 6.0.4 on 2026-04-23 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0026_chat_loaded_skill_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalToolApprovalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_call_id", models.CharField(max_length=255)),
                (
                    "approval_request_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("tool_name", models.CharField(max_length=255)),
                ("tool_label", models.CharField(blank=True, max_length=255)),
                ("external_service_name", models.CharField(blank=True, max_length=255)),
                ("query", models.TextField(blank=True)),
                ("tool_arguments", models.JSONField(blank=True, default=dict)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("auto_approved", "Auto-approved"),
                            ("approved", "Manually approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approval_source", models.CharField(blank=True, max_length=64)),
                ("pii_flagged", models.BooleanField(default=False)),
                ("displayed_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_tool_approval_logs",
                        to="chat_next.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_next_external_tool_approval_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="chat_next_e_created_244490_idx"
                    ),
                    models.Index(
                        fields=["decision", "created_at"],
                        name="chat_next_e_decisio_7ca07b_idx",
                    ),
                    models.Index(
                        fields=["tool_name", "created_at"],
                        name="chat_next_e_tool_na_9cf6c6_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "tool_call_id"),
                        name="chat_next_external_tool_approval_log_per_call",
                    )
                ],
            },
        ),
    ]
