# Generated by Django 6.0.4 on 2026-04-23 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_external_tool_approval_log_fields(apps, schema_editor):
    ExternalToolApprovalLog = apps.get_model("chat_next", "ExternalToolApprovalLog")

    for log in ExternalToolApprovalLog.objects.all().iterator():
        fields_to_update = []

        if log.message_id_snapshot is None and log.message_id is not None:
            log.message_id_snapshot = log.message_id
            fields_to_update.append("message_id_snapshot")

        if log.pii_flagged and log.pii_flag_source == "no":
            log.pii_flag_source = "llm"
            fields_to_update.append("pii_flag_source")

        if fields_to_update:
            log.save(update_fields=fields_to_update)


class Migration(migrations.Migration):

    dependencies = [
        ("chat_next", "0027_externaltoolapprovallog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="externaltoolapprovallog",
            name="chat_next_external_tool_approval_log_per_call",
        ),
        migrations.AddField(
            model_name="externaltoolapprovallog",
            name="message_id_snapshot",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="externaltoolapprovallog",
            name="pii_flag_source",
            field=models.CharField(
                choices=[
                    ("no", "No"),
                    ("llm", "LLM"),
                    ("local_checks", "Local checks"),
                    ("azure_language_api", "Azure Language API"),
                ],
                default="no",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="externaltoolapprovallog",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_tool_approval_logs",
                to="chat_next.message",
            ),
        ),
        migrations.RunPython(
            backfill_external_tool_approval_log_fields,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="externaltoolapprovallog",
            index=models.Index(
                fields=["message_id_snapshot"], name="chat_next_e_message_8fe4e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externaltoolapprovallog",
            index=models.Index(
                fields=["user", "created_at"], name="chat_next_e_user_id_99f72a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externaltoolapprovallog",
            index=models.Index(
                fields=["pii_flagged", "created_at"],
                name="chat_next_e_pii_fla_a9430b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="externaltoolapprovallog",
            constraint=models.UniqueConstraint(
                fields=("message_id_snapshot", "tool_call_id", "decision"),
                name="chat_next_external_tool_approval_log_per_event",
            ),
        ),
    ]
