# Generated by Django 6.0.4 on 2026-04-23 14:37

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Max


def dedupe_external_tool_approval_logs(apps, schema_editor):
    ExternalToolApprovalLog = apps.get_model("chat_next", "ExternalToolApprovalLog")

    duplicate_groups = (
        ExternalToolApprovalLog.objects.exclude(message_id_snapshot__isnull=True)
        .values("message_id_snapshot", "tool_call_id")
        .annotate(total=Count("id"), keep_id=Max("id"))
        .filter(total__gt=1)
    )

    for group in duplicate_groups.iterator():
        (
            ExternalToolApprovalLog.objects.filter(
                message_id_snapshot=group["message_id_snapshot"],
                tool_call_id=group["tool_call_id"],
            )
            .exclude(id=group["keep_id"])
            .delete()
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat_next",
            "0028_remove_externaltoolapprovallog_chat_next_external_tool_approval_log_per_call_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="externaltoolapprovallog",
            name="chat_next_external_tool_approval_log_per_event",
        ),
        migrations.RunPython(
            dedupe_external_tool_approval_logs,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="externaltoolapprovallog",
            constraint=models.UniqueConstraint(
                fields=("message_id_snapshot", "tool_call_id"),
                name="chat_next_external_tool_approval_log_per_snapshot_call",
            ),
        ),
    ]
