name: Django Localization CI
# See https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers

on:
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash 
    working-directory: ./django
  
env:
  AZURE_OPENAI_KEY: ${{secrets.AZURE_OPENAI_KEY}}
  AZURE_COGNITIVE_SERVICE_KEY: ${{secrets.AZURE_COGNITIVE_SERVICE_KEY}}      
  LOG_LEVEL: ERROR
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  load-localization:    
    runs-on: ubuntu-latest
    container: python:3.11
    # job should run only when the PR is not created by the bot
    if: github.event.actor != 'github-actions[bot]' && github.event_name == 'pull_request'
    permissions:
      contents: write
      pull-requests: write
      actions: read
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y gettext
        python -m pip install --upgrade pip
        pip install -r requirements.txt        
    - name: Run load_app_localization command
      run: |
        python manage.py load_app_localization
    - name: Commit changes
      run: |
        git config --global --add safe.directory /__w/otto/otto
        git config --global user.name "github-actions[bot]"        
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Update localization files"
          git push
        else
          echo "No changes to commit"
        fi
