name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "cloud" ]

defaults:
  run:
    shell: bash
    working-directory: ./django

jobs:
  test:
    env:
      AZURE_OPENAI_KEY: ${{secrets.AZURE_OPENAI_KEY}}
      AZURE_COGNITIVE_SERVICE_KEY: ${{secrets.AZURE_COGNITIVE_SERVICE_KEY}}
    runs-on: ubuntu-latest
    name: Build, test and report coverage
    permissions:
      # So that the action can add a comment to the PR
      pull-requests: write
      # Needs to push data to python-coverage-comment-action branch
      contents: write
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
      # TODO: Not installing Poppler here because the tests that require it are skipped
      # sudo apt-get update
      # sudo apt-get install -y poppler-utils
    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput
    - name: Run tests
      working-directory: ./
      run: |
        python -m coverage run --source=django -m pytest -k "not skip_on_github_actions" django
    - name: Display coverage
      working-directory: ./
      run: |
        python -m coverage report -m
    - name: Coverage comment
      id: coverage_comment
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Store Pull Request comment to be posted
      uses: actions/upload-artifact@v3
      if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
      with:
        name: python-coverage-comment-action
        path: python-coverage-comment-action.txt
  